<?php
	//----------------------- INPUT ELEMENTS -------------------//
	$ssFilter 		= $this->arrParam['ssFilter'];
	$selectLanguages = $ssFilter['lang_code'] . $this->formHidden('lang_code',$ssFilter['lang_code']);
	$video 			= $this->formText ( 'video', $this->Item['video'], array ('class' => 'txtshort') );
    $name 			= $this->formText ( 'name', $this->Item['name'], array ('class' => 'txtlong active', 'onchange'=>"get_alias()") );
	$picture		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture" class="hinh-anh"></div>';
	if(!empty($this->Item['picture'])){
		$picture	= '<div><img src="' . $this->Item['picture'] . '" id="image_picture" class="hinh-anh"></div>';
	}
	$picture 		= $this->cmsUserFiles('picture', $this->Item['picture'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture;
    
    $picture_mobile		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture_mobile" class="hinh-anh"></div>';
	if(!empty($this->Item['picture_mobile'])){
		$picture_mobile	= '<div><img src="' . $this->Item['picture_mobile'] . '" id="image_picture_mobile" class="hinh-anh"></div>';
	}
	$picture_mobile 		= $this->cmsUserFiles('picture_mobile', $this->Item['picture_mobile'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture_mobile;
    
	$option 		= array('Không','Có');
	if(isset($this->Item['status'])){
		$trangthai = $this->Item['status'];
	}else{
		$trangthai = 1;
	}
	$status 		= $this->formRadio('status',$trangthai,null,$option, ' ');
	if(isset($this->Item['order'])){
		$order = $this->Item['order'];
	}else{
		$order = 255;
	}
    //var_dump($this->slbPage);die;
    $page	= $this->formSelect('page_id',$this->Item['page_id'],array('style'=>'width:250px;'),$this->slbPage);
   // $slbDiadiemThoigian	= $this->formSelect('time_id',$this->Item['time_id'],array('style'=>'width:250px;'),$this->slbDiadiemThoigian);        
	$order 			= $this->formText ('order', $order, array ('class' => 'txtshort' ) );
	$selectCategory	= $this->cmsSelect('cat_id',$this->Item['cat_id'],$this->slbCategory,array('size'=>0,'style'=>'min-width:200px;'));
	$author 		= $this->formText ( 'author', $this->Item['author'], array ('class' => 'txtmedium') );
	$synopsis		= $this->formTextarea('synopsis', $this->Item['synopsis'],array('rows'=>4,'class' => 'textarea','maxlength'=>'140'));
	
	$content 		= $this->cmsEditor('content',htmlspecialchars_decode($this->Item['content']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
	$tungay = $this->formText('ngaysudung',$this->Item['ngaysudung'],array('class'=>'txtlong hasDatePicker ','style' => 'margin-left:3px; width:70px;','placeholder' => 'MM/DD/YY'));
    $coupon 		= $this->formText ( 'coupon', $this->Item['coupon'], array ('class' => 'txtmedium') );
    $link 		= $this->formText ( 'link', $this->Item['link'], array ('class' => 'txtmedium') );
    //var_dump($this->ItemEn);die;
    $name_en 			= $this->formText ( 'name_en', $this->ItemEn['name'], array ('class' => 'txtlong active', 'onchange'=>"get_alias()") );
    $synopsis_en		= $this->formTextarea('synopsis_en', $this->ItemEn['synopsis'],array('rows'=>4,'class' => 'textarea','maxlength'=>'140'));
    $content_en 		= $this->cmsEditor('content_en',htmlspecialchars_decode($this->ItemEn['content']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
	$arrInput = array(
				array('label' => 'Chọn ngôn ngữ','input' => $selectLanguages),
				array('label' => 'Tiêu đề','input' => $name, 'desc' => '<span class="red">*</span>'),
				array('label' => 'Hình ảnh minh họa PC','input' => $picture),
                array('label' => 'Hình ảnh minh họa mobile','input' => $picture_mobile),
				array('label' => 'Thuộc danh mục','input' => '<div id="category">' . $selectCategory . '</div>'),
                array('label' => 'ID Youtube','input' => $video),
                array('label' => 'Thuộc Page','input' => '<div id="category">' . $page . '</div>'),
                
				array('label' => 'Hiển thị','input' => $status),
				array('label' => 'Thứ tự','input' => $order),
				array('label' => 'Tác giả','input' => $author),
				array('label' => 'Giới thiệu ngắn','input' => $synopsis, 'cols' => 2,'style' => 'padding-top:0;'),
				array('label' => 'Nội dung','input' => $content, 'cols' => 2,'style' => 'padding-top:0;'),
			);
            
   $arrInputEn = array(
				array('label' => 'Tiêu đề','input' => $name_en, 'desc' => '<span class="red">*</span>'),
				array('label' => 'Giới thiệu ngắn','input' => $synopsis_en, 'cols' => 2,'style' => 'padding-top:0;'),
				array('label' => 'Nội dung','input' => $content_en, 'cols' => 2,'style' => 'padding-top:0;'),
			);
	
	//--------------------- Blocks ---------------------
	$option 			= array('Không','Có');
	if(isset($this->Item['block_noibat'])){
		$trangthai = $this->Item['block_noibat'];
	}else{
		$trangthai = 0;
	}
	$blockNoiBat		= $this->formRadio('block_noibat',$trangthai,null,$option, ' ');
	
	if(isset($this->Item['block_hot'])){
		$trangthai = $this->Item['block_hot'];
	}else{
		$trangthai = 0;
	}
	$blockHot 			= $this->formRadio('block_hot',$trangthai,null,$option, ' ');
	
	$arrBlock = array(
			array('label' => 'Tin nổi bật','input' => $blockNoiBat),
			array('label' => 'Tin hot(Tin Banner)','input' => $blockHot),
	);

	//--------------------- Meta Options ---------------------
	$alias 				= $this->formText ( 'alias', $this->Item['alias'], array ('class' => 'textlong' ) );
	$tags		 		= $this->formTextarea('tags',$this->Item['tags'],array('rows'=>2,'class' => 'txtalong'));
	$meta_title 		= $this->formTextarea('meta_title',$this->Item['meta_title'],array('rows'=>2,'class' => 'txtalong'));
	$meta_description 	= $this->formTextarea('meta_description',$this->Item['meta_description'],array('rows'=>3,'class' => 'txtalong'));
	$meta_keywords 		= $this->formTextarea('meta_keywords',$this->Item['meta_keywords'],array('rows'=>3,'class' => 'txtalong'));
	
	$arrMeta = array(
			array('label' => 'Liên kết tĩnh','input' => $alias),
			array('label' => 'Tags','input' => $tags,'desc'=>'Mỗi Tags phân biệt nhau với dấu phẩy'),
			array('label' => 'Meta Title','input' => $meta_title),
			array('label' => 'Meta Description','input' => $meta_description),
			array('label' => 'Meta Keywords','input' => $meta_keywords),
		);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-item/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-item/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<div class="width-60 fl">
            <script>
				$(document).ready(function() {
					$(".tabs-nav li:first a").addClass('selected');
					$(".tabs:first").css('display','block');
				    $(".tabs-nav li a").click(function() {
				        $(".tabs-nav li a").removeClass('selected');
				        $(this).addClass('selected');
				        $(".tabs").css('display','none');
				        $($(this).attr("rel")).css('display','block');
				        
				    	return false;
				    });
				});
			</script>
            <ul class="tabs-nav clearfix">
				<li><a rel="#tabs-1" href="javascript:void(0)">Vietnamese</a></li>
				<li><a rel="#tabs-2" href="javascript:void(0)">English</a></li>
				
			</ul>
			<fieldset class="adminform tabs" id="tabs-1">
				
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInput);?>
				</table>
			</fieldset>
            <fieldset class="adminform tabs" id="tabs-2">
				
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInputEn);?>
				</table>
			</fieldset>
		</div>
		<div class="width-40 fr">
			<div id="pane-sliders" class="pane-sliders">
				
				<div class="panel">
					<h3 id="metadata-options" class="title pane-toggler-down"><a href="javascript:void(0);"><span>Danh mục thuộc các block</span></a></h3>
					<div class="panel_content">
						<fieldset class="panelform">
							<table class="panelformlist">
								<?php echo $this->partialLoop('row.php', $arrBlock);?>
							</table>
						</fieldset>
					</div>
				</div>
				
				<div class="panel">
					<h3 id="metadata-options" class="title pane-toggler-down"><a href="javascript:void(0);"><span>Metadata Options</span></a></h3>
					<div class="panel_content">
						<fieldset class="panelform">
							<table class="panelformlist">
								<?php echo $this->partialLoop('row.php', $arrMeta);?>
							</table>
						</fieldset>
					</div>
				</div>
					
			</div>
		</div>
		<div class="clr"></div>
	</div>
	<!-- END: 	CONTENT -->
</form>
<script>

//date
$(".hasDatePicker").datepicker({ 
	dateFormat: 'yy/mm/dd',
	changeMonth: true,
	changeYear: true,
	yearRange: "-100:+2"
});
 						
</script>