<?php
	$moduleConfig = $this->arrParam['moduleConfig'];
?>
	<div class="module_dia_diem">
		<div class="module_title clearfix">
			<span class="icon"></span> 
			<h1 class="title"><?php echo $this->language['diadiemHot'];?></h1>
		</div>
		<div class="module_content">
			<ul class="dia_diem_an_choi clearfix">
			<?php
			foreach ($this->Items as $key => $val){
				$name = $val['name'];
				$code = '';
				if($val['code'] != ''){
					$code = '<p class="code">'.$this->language['productMaSanPham'].': ' . $val['code'] . '</p>';
				}
				$picture = '<img class="img" src="' . $val['picture'] . '" alt="'.$val['name'].'"/>';
					
				$synopsis = $val['synopsis'];
				$units_money = $val['units_money'];
				$price = '';
				
				if($val['price'] != 0){
					$price = '<p class="price">'.$this->language['diadiemGia'].': <span class="value">'.Zend_Locale_Format::toNumber($val['price'],array('precision' => 0)) . ' ' . $units_money.'</span></p>';
				}else{
					$price = '<p class="price">'.$this->language['diadiemGia'].': <span class="value">'.$this->language['lienHe'].'</span></p>';
				}
				
				$selloff = '';
				if($val['selloff'] > 0){
					$selloff = '<p class="d_cat_name"><span>' . $val['selloff'] . '%</span></p>';
				}
				
				$addCart = '';
				if($moduleConfig['showAddCart'] == 1){
					$linkCart = $this->baseUrl('diadiem/public/add-item/id/' . $val['id']);
					$addCart = '<a href="'.$linkCart.'" title="'.$this->language['diadiemDatCho'].' '.$name.'" class="addCart" rel="nofollow">'.$this->language['diadiemDatCho'].'</a>';
				}
					
				$urlOptions = array (
						'module' => 'diadiem',
						'controller' => 'index',
						'action' => 'detail',
						'tcat' => $val ['category_alias'],
						'title' => $val ['alias'],
						'cid' => $val ['cat_id'],
						'id' => $val ['id'] );
				$linkDetial = $this->url( $urlOptions, 'diadiem-detail' );
			?>
				<li class="item">
					<div class="dd_content">
						<div class="d_images">
							<a href="<?php echo $linkDetial;?>" title="<?php echo $name;?>">
								<?php echo $picture;?>
							</a>
						</div>
						<h4 class="d_title"><a href="<?php echo $linkDetial;?>" title="<?php echo $name;?>"><?php echo $name;?></a></h4>
						<div class="d_price">
							<?php echo $price;?>
						</div>
						<p class="d_detail">
							<?php echo $addCart;?>
							<a href="<?php echo $linkDetial;?>" title="<?php echo $name;?>" class="detail"><?php echo $this->language['chiTiet'];?></a>
						</p>
						<?php echo $selloff;?>
					</div>
				</li>
			<?php
				} 
			?>
			</ul>
			<?php
				$currentUrl = $this->baseUrl('diadiem/block/' . $this->arrParam['action']);
				echo $this->paginationControl($this->paginator,'Sliding','pagination-index.phtml',array('currentUrl'=>$currentUrl,'arrParam' => $this->arrParam)); 
			?>
		</div>
		<div class="module_bottom"></div>
	</div>