<?php
	//Xay dung tim kiem
	$ssFilter 		= $this->arrParam['ssFilter'];
	$page = '';
	if(isset($this->arrParam['page'])){
		$page = '/page/' . $this->arrParam['page'];
	}
	$product_id = '';
	if(isset($this->arrParam['product_id'])){
		$page = '/product_id/' . $this->arrParam['product_id'];
	}
	$url = $page . $product_id;
	$action_link 	= $this->baseUrl($this->currentController . '/filter/type/order' . $url);
	$lblName 		= $this->cmsLinkSort('Tên','gi.name',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$lblID 			= $this->cmsLinkSort('ID','gi.id',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$lblStatus 		= $this->cmsLinkSort('Phân khu','gi.status',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblOrder 		= $this->cmsLinkSort('Sản phẩm','gi.order',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblCategory	= $this->cmsLinkSort('Danh mục','category_name',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblhits		= $this->cmsLinkSort('Lượt xem','gi.hits',$ssFilter,$this->imgUrl . '/admin',$action_link);
	$lblLanguage	= $this->cmsLinkSort('Ngôn ngữ','gi.lang_code',$ssFilter,$this->imgUrl . '/admin',$action_link);
	
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSerach = $this->formButton('search-now','Tìm',array('onclick'=>"OnSubmitForm('" .$linkSearch . "')"));
	
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');
	$btnResetSerach = $this->formButton('clear-keywords','Xóa',array('onclick'=>"OnSubmitForm('" .$linkResetSearch ."')"));
	
	$strSearch = $keywords . ' ' . $btnSerach . ' ' . $btnResetSerach;

	$strSearchRight = '';
?>
<form name="appForm" method="post" action="">
	<?php echo $this->render('admin-image/toolbar/image.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-image/sublink/index.php');?>	

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<table class="adminlist">
			<tr>
				<th width="20">#</th>
				<th width="20">
					<input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()">
				</th>
			
				<th width="60"><?php echo $lblName;?></th>
				<th width="160">Phân khu</th>
				<th width="160">Sản phẩm</th>
				<th width="70">Control</th>
				<th width="34"><?php echo $lblID;?></th>
			</tr>
			<?php
				foreach ($this->Items as $key => $val){
					$id 			= $val['id'];
					$name 			= $val['name'];
					$tenphankhu		= htmlspecialchars_decode($val['tenphankhu']);
					$tensanpham			= $val['tensanpham'];
					$linkInfo		= $this->baseUrl($this->currentController . '/info/id/' . $id . $url);
					$btnInfo		= $this->cmsIconButton('Xem thông tin', $this->imgUrl . '/admin/icon_info.png', $linkInfo);
					$linkEdit		= $this->baseUrl($this->currentController . '/edit/id/' . $id . $url);
					$btnEdit		= $this->cmsIconButton('Sửa', $this->imgUrl . '/admin/icon_edit.png', $linkEdit);
					$linkDelete		= $this->baseUrl($this->currentController . '/delete/id/' . $id . $url);
					$btnDelete		= $this->cmsIconButton('Xóa', $this->imgUrl . '/admin/publish_r.png', $linkDelete);
					$strIconButton 	= $btnEdit . ' ' . $btnDelete;
					$name 	= '<b><a href="' . $linkEdit . '">' . $name . '</a></b>';
					
					$cid 			= $this->formCheckbox('cid[]',$val['id']);
					
					$classRow = 'row1';
					if($key % 2 == 0)
						$classRow = 'row0';
					
			?>
			<tr class="<?php echo $classRow;?>">
				<td align="center"><?php echo $key + 1;?></td>
				<td align="center"><?php echo $cid;?></td>
				<td align="left"><?php echo $name;?></td>
				<td align="center"><?php echo $tenphankhu;?></td>
				<td align="center"><?php echo $tensanpham;?></td>
				<td align="center"><?php echo $strIconButton;?></td>
				<td align="center"><?php echo $id;?></td>
			</tr>
			<?php
				} 
			?>
			<tr class="tbl_footer">
				<td colspan="12">
					<div class="container">
						<div class="pagination">
							<?php
								$album_id = '';
								if(isset($this->arrParam['album_id'])){
									$album_id = '/album_id/' . $this->arrParam['album_id'];
								}
								$currentUrl = $this->baseUrl($this->currentController . '/index' . $album_id);
								echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl)); 
								?>
							<div class="limit"></div>
						</div>
					</div>
				</td>
			</tr>
		</table>
		<div class="clr"></div>
	</div>
	<!-- END: 	CONTENT -->
</form>