<div class="top">
	<p><?php echo $this->category['name']; ?> <span><?php echo $this->totalItem; ?></span> sản phẩm</p>
</div>
<div class="content">
    <div class="row">
	
			<?php
			foreach ($this->Items as $key => $val){
				$name = $val['name'];
			
				$code = '';
				if($val['code'] != ''){
					$code = '<p class="sku">'.$this->language['productMaSanPham'].': ' . $val['code'] . '</p>';
				}
				$imgName = explode ( '/editor-upload/images/', $val ['picture'] ); 
				$picture = '<img  class="img" src="' . APPLICATION_URL . '/default/public/view-image/width/358/height/313/images/' . $imgName [1] . '" alt="' . $val ['name'] . '"/>';
			
				$synopsis = nl2br($val['synopsis']);
				$units_money = $val['units_money'];
				//$quanhuyen_name =$val['quanhuyen_name'];
				$price = '';
				if($val['price'] != 0){
					$price = '<p class="price">'.Zend_Locale_Format::toNumber($val['price'],array('precision' => 0)) . ' ' . $units_money.'</p>';
				}else{
					$price = '<p class="price">'.$this->language['lienHe'].'</p>';
				}
				
				
				
				$urlOptions = array (
						'module' => 'diadiem',
						'controller' => 'index',
						'action' => 'detail',
						'title' => $val ['alias'],
						'id' => $val ['id'] );
				$linkDetial = $this->url( $urlOptions, 'diadiem-detail' );
				
				?>
				<div class="col-sm-4">
					<div class="item-sp">
						<div class="image">
							<a href="<?php echo $linkDetial; ?> "><?php echo $picture ?></a>
						</div>
						<div class="info">
							<h3><a href="<?php echo $linkDetial; ?>"><?php echo $name; ?></a></h3>
							<?php echo $code; ?>
							<?php echo $price; ?>
						</div>
					</div>
				</div>
			<?php
				} 
			?>
	   </div>
       </div>
		<?php
			//if(!empty($this->arrParam['cid'])){
					
				//$urlOptionsCategory = array('module'=>'diadiem','controller'=>'index','action'=>'category',
					//	'cid'=>$this->arrParam['cid'],
					//	'alias'=>$this->arrParam['alias'],
			//	);
			//	$currentUrl = $this->url($urlOptionsCategory,'diadiem-category');
			//}else{
			//	$currentUrl = 'diadiem.html';
			//}
			//echo $this->paginationControl($this->paginator,'Sliding','pagination-index.phtml',array('currentUrl'=>$currentUrl,'arrParam' => $this->arrParam)); 
		?>

	