
<div class="block_thongTinTaiKhoan">
	<div class="block_title"><?php echo $this->Title;?></div>
	<div class="block_content article_manager">
		 
			<div class="item">
				<div class="item_content">
					
					
				
				
				<?php
	//----------------------- INPUT ELEMENTS -------------------//
	$name 			= $this->formText ( 'name', $this->Item['name'], array ('class' => 'txtlong active', 'onchange'=>"get_alias()") );
	$picture		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture" class="hinh-anh"></div>';
	if(!empty($this->Item['picture'])){
		$picture		= '<div><img src="' . $this->Item['picture'] . '" id="image_picture" class="hinh-anh"></div>';
	}
	$picture 		= $this->cmsUserFiles('picture', $this->Item['picture'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture;
	$selectCategory	= $this->cmsSelect('cat_id',$this->Item['cat_id'],$this->slbCategory,array('size'=>0,'style'=>'min-width:200px;','onchange'=>"loadShop(this.value)"));
	$optionsUnits 	= $this->slbDiadiemUnits;
	$slbMoney		= $this->formSelect('units_money',$this->Item['units_money'],array(),$this->slbMoney);
	$selloff		= ' Giảm giá ' . $this->formText ('selloff', $this->Item['selloff'], array ('class' => 'txtshort auto_numberic' , 'style'=>'width:20px;', 'maxlength' => 2) ) . ' %';
// 	$vat = array(
// 			'1' => 'Đã bao gồm VAT',
// 			'0'=> 'Chua bao gồm VAT',
// 	);
// 	$selectVat = $this->formSelect('vat',$this->Item['vat'],array(),$vat);
// 	$price 			= $this->formText ('price',  Zend_Locale_Format::toNumber($this->Item['price'],array('precision' => 0)), array ('class' => 'txtshort auto_numberic') ) . ' ' . $slbMoney . ' ' . $selloff . ' ' .$selectVat;
	$slbDiadiemUnits= $this->formSelect('unit_id',$this->Item['unit_id'],array(),$this->slbDiadiemUnits);
	//$diadiem_number	= $this->formText ('diadiem_number', $this->Item['diadiem_number'], array ('class' => 'txtshort auto_numberic') ) . ' ' . $slbDiadiemUnits;
	
	$price 			= $this->formText ('price',  Zend_Locale_Format::toNumber($this->Item['price'],array('precision' => 0)), array ('class' => 'txtshort auto_numberic') ) . ' ' . $slbMoney . ' / 01 '.$slbDiadiemUnits . $selloff ;
	 
	$slbSourcesMoney	= $this->formSelect('sources_money',$this->Item['sources_money'],array(),$this->slbMoney);
	//		= ' Giá nhập vào ' . $this->formText ('money_sources', Zend_Locale_Format::toNumber($this->Item['money_sources'],array('precision'=>0)), array ('class' => 'txtshort auto_numberic') ) . ' ' . $slbSourcesMoney;
	//$slbDiadiemSources	= $this->formSelect('sources_id',$this->Item['sources_id'],array('style'=>'width:250px;'),$this->slbDiadiemSources) . ' ' . $moneySources;
	//$slbDiadiemSources	= $this->formSelect('sources_id',$this->Item['sources_id'],array('style'=>'width:250px;'),$this->slbDiadiemSources);
	$slbDiadiemManu		= $this->formSelect('manu_id',$this->Item['manu_id'],array('style'=>'width:250px;'),$this->slbDiadiemManu);
	
	$synopsis		= $this->formTextarea('synopsis', $this->Item['synopsis'],array('rows'=>4,'class' => 'textarea synopsis'));
	
	$content 		= $this->cmsEditor('content',htmlspecialchars_decode($this->Item['content']),array('class'=>'content','toolbar'=>'MyToolbar', 'language'=>'vi'));
	
	$arrInput = array(
				array('label' => 'Tiêu đề','input' => $name, 'desc' => '<span class="red">*</span>'),
				array('label' => 'Hình ảnh minh họa','input' => $picture),
				array('label' => 'Chọn danh mục quán','input' => '<span id="category">' . $selectCategory . '</span>'),
				array('label' => 'Giá ','input' => $price),
				//array('label' => 'Số lượng trong kho','input' => $diadiem_number . ' Tình trạng ' . $selectTinhTrang),
				 
// 				array('label' => 'Bảo hành','input' => $baohanh_number),
// 				array('label' => 'Vận chuyển','input' => $vanchuyen),
// 				array('label' => 'Khuyễn mại','input' => $khuyenmai),
				array('label' => 'Chọn kiểu nhà hàng','input' => $slbDiadiemManu),  
				array('label' => 'Giới thiệu ngắn','input' => $synopsis, 'cols' => 2,'style' => 'padding-top:0;','desc' => 'Được hiển thị khi xem chi tiết hoặc xem ở dạng danh sách'),
				array('label' => 'Nội dung','input' => $content, 'cols' => 2,'style' => 'padding-top:0;'),
			);
	
	 
	//-------------------- Hinh anh ------------------------//
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content  ">
		<div class="fl">
			<script>
				$(document).ready(function() {
					$(".tabs-nav li:first a").addClass('selected');
					$(".tabs:first").css('display','block');
				    $(".tabs-nav li a").click(function() {
				        $(".tabs-nav li a").removeClass('selected');
				        $(this).addClass('selected');
				        $(".tabs").css('display','none');
				        $($(this).attr("rel")).css('display','block');
				        
				    	return false;
				    });
				});
			</script>
			<ul class="tabs-nav clearfix">
				<li><a rel="#tabs-1" href="javascript:void(0)">Thông tin chung</a></li>
				<li><a rel="#tabs-2" href="javascript:void(0)">Hình ảnh</a></li>
			</ul>
			<fieldset class="article-form tabs" id="tabs-1">
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInput);?>
				</table>
			</fieldset>
			<fieldset class="adminform tabs" id="tabs-2">
				<ul class="adminformlist" id="imagelist">
					<?php
					$numberImage = 0;
					if(count($this->Item['picture_multi']) > 0){
						$numberImage = count($this->Item['picture_multi']);
						foreach(unserialize($this->Item['picture_multi']) AS $key => $val){
							$picture		= '<div><img src="' . $val[0] . '" id="image_picture_multi'.$key.'" class="hinh-anh" style="width:60px;"></div>';
					?>
					<li id="picture<?php echo $key;?>">
						<script type="text/javascript">
						function openKCFinder<?php echo $key;?>(field) {
							$('#formLoading').removeClass().addClass('loading').fadeIn();
							window.KCFinder = {
								callBack: function(url) {
									field.value = url;
									window.KCFinder = null;
									document.getElementById('image_picture_multi<?php echo $key;?>').src = url;
								}
							};
							window.open('<?php echo SCIPTS_URL . '/media_files/browse.php?type=images&lng=vi';?>', 'kcfinder_textbox','status=0, toolbar=0, location=0, menubar=0, directories=0,resizable=1, scrollbars=0, width=950, height=450' );
							$('#formLoading').removeClass().fadeOut();
						}</script>
						<div>
							<input value="<?php echo $val[0];?>" type="text" name="picture_multi[]" id="picture_multi<?php echo $key;?>" class="txtfile"><a href="javascript:void(0);" onclick="openKCFinder<?php echo $key;?>(appForm.picture_multi<?php echo $key;?>)" class="btnMedia">Chọn ảnh</a><span class="pdl20">Thứ tự <input type="text" name="orderImage[]" style="width: 50px;" value="<?php echo $this->Item['orderImage'][$key];?>"></span><span class="pdl20"><a href="javascript:void(0);" onclick="javascript:Delete(<?php echo $key;?>);">[Xóa]</a></span>
						</div>
						<div class="clr"></div>
						<?php echo $picture;?>
					</li>
					<?php
						}
					} 
					?>
				</ul>
				<div class="fr">
					<a href="javascript:void(0);" onclick="creatImage()" class="btnMedia">Thêm ảnh</a>
				</div>
				<input type="hidden" name="numberImage" id="numberImage" value="<?php echo $numberImage;?>">
				<script type="text/javascript">
					function creatImage(){
						//alert('hic');
						var picture = '<li id="picture{i}">'+
							'<script type="text/javascript">'+
							'function openKCFinder{i}(field) {'+
								'$(\'#formLoading\').removeClass().addClass(\'loading\').fadeIn();'+
								'window.KCFinder = {'+
									'callBack: function(url) {'+
										'field.value = url;'+
										'window.KCFinder = null;'+
										'document.getElementById(\'image_picture_multi{i}\').src = url;'+
									'}'+
								'};'+
								'window.open(\'<?php echo SCIPTS_URL . '/media_files/browse.php?type=images&lng=vi';?>\', \'kcfinder_textbox\',\'status=0, toolbar=0, location=0, menubar=0, directories=0,resizable=1, scrollbars=0, width=950, height=450\');'+
								'$(\'#formLoading\').removeClass().fadeOut();'+
							'}<\/script>'+
							'<div>'+
								'<input value="" type="text" name="picture_multi[]" id="picture_multi{i}" class="txtfile">'+
								'<a href="javascript:void(0);" onclick="openKCFinder{i}(appForm.picture_multi{i})" class="btnMedia">Chọn ảnh</a>'+
								'<span class="pdl20">Thứ tự <input type="text" name="orderImage[]" style="width: 50px;" value="0"></span>'+
								'<span class="pdl20">'+
									'<a href="javascript:void(0);" onclick="javascript:Delete({i});">[Xóa]</a>'+
								'</span>'+
							'</div>'+
							'<div class="clr"></div>'+
							'<div><img src="<?php echo $this->imgUrl . '/no-avatar.png';?>" id="image_picture_multi{i}" class="hinh-anh" style="width: 60px;"></div>'+
						'</li>';
						var i = parseInt($('#numberImage').val());
						var str = picture;
						str = str.replace(/{i}/gi,i);
						str = str.replace(/{i2}/gi,i+1);
						$('#imagelist').append(str);
						$('#numberImage').val(i+1);
					}
					function Delete(i) {
						$('#picture'+i).remove();
					}
				</script>
			</fieldset>
			 
		</div>
	 
	</div>
	<!-- END: 	CONTENT -->
</form>
				
				
				
				
				
				
				
				
					
				</div>
			</div> 
			<div class="clr"></div>
	</div>
</div>