<?php
	//----------------------- INPUT ELEMENTS -------------------//
    
	$ssFilter 		= $this->arrParam['ssFilter'];
	$selectLanguages = $ssFilter['lang_code'] . $this->formHidden('lang_code',$ssFilter['lang_code']);
	$name 			= $this->formText ( 'name', $this->Item['name'], array ('class' => 'txtlong active', 'onchange'=>"get_alias()") );
	
	$option 		= array('Không','Có');
	if(isset($this->Item['status'])){
		$trangthai = $this->Item['status'];
	}else{
		$trangthai = 1;
	}
	$status 		= $this->formRadio('status',$trangthai,null,$option, ' ');
	
	if(isset($this->Item['order'])){
		$order = $this->Item['order'];
	}else{
		$order = 255;
	}
	$order 			= $this->formText ('order', $order, array ('class' => 'txtshort' ) );
	
	$picture 		= $this->cmsUserFiles('picture', $this->Item['picture'], 'Chọn ảnh', 'file', $options = array('class' => 'txtfile') ) . $picture;
	
	$content 		= $this->cmsEditor('content',htmlspecialchars_decode($this->Item['content']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    $tongquan 		= "<textarea id= 'tongquan' name='tongquan'>". htmlspecialchars_decode($this->Item['tongquan']) ."</textarea>";
    $hocphi 		= "<textarea id= 'hocphi' name='hocphi'>". htmlspecialchars_decode($this->Item['hocphi']) ."</textarea>";
    $dangki 		= "<textarea id= 'dangki' name='dangki'>". htmlspecialchars_decode($this->Item['dangki']) ."</textarea>";
	
	$arrInput = array(
				//array('label' => 'Chọn ngôn ngữ','input' => $selectLanguages),
				array('label' => 'Tên','input' => $name, 'desc' => '<span class="red">*</span>'),
				array('label' => 'Hiển thị','input' => $status),
				array('label' => 'Thứ tự','input' => $order),
                
                array('label' => 'Hình ảnh','input' => $picture),
                array('label' => 'Tổng quan','input' => $tongquan, 'cols' => 2,'style' => 'padding-top:0;'), 
                               
				array('label' => 'Nội dung','input' => $content, 'cols' => 2,'style' => 'padding-top:0;'),
                array('label' => 'Học phí','input' => $hocphi, 'cols' => 2,'style' => 'padding-top:0;'),
                array('label' => 'Đăng kí','input' => $dangki, 'cols' => 2,'style' => 'padding-top:0;'),
			);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-khoahoc/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $this->render('admin-khoahoc/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<fieldset class="adminform">
			<legend>Chi tiết</legend>
			<table class="adminformlist">
				<?php echo $this->partialLoop('row.php', $arrInput);?>
			</table>
		</fieldset>
	</div>
	<!-- END: 	CONTENT -->
     <script>
        //<![CDATA[

				// This call can be placed at any point after the
				// <textarea>, or inside a <head><script> in a
				// window.onload event handler.

				// Replace the <textarea id="editor"> with an CKEditor
				// instance, using default configurations.
			//	CKEDITOR.replace( 'editor1' );

			//]]>
            CKEDITOR.replace('tongquan');
         CKEDITOR.replace('hocphi');
         CKEDITOR.replace('dangki');
    </script>
</form>