<?php
 
if ($this->totalItem > 0) { 
?>
<div class="module_article">
	<div class="module_title clearfix">
		<span class="icon"></span>
		<?php 
		if(!empty($this->arrParam[keywords])){$string = ' "'.$this->arrParam[keywords].'"'; }
		?>
		<h1 class="title"><?php echo $this->language['ketQuaTimKiem'].$string;?></h1>
	</div>
	<div class="module_content pd5">
	<?php
			foreach ( $this->Items as $key => $val ) {
			$name = $val ['name'];
			$picture = '<img class="img" src="' . $val ['picture'] . '" alt="' . $val ['name'] . '"/>';
			if($val ['thumb'] != ''){
				$picture = '<img class="img" src="' . $val ['thumb'] . '" alt="' . $val ['name'] . '"/>';
			}
			$synopsis = nl2br($val ['synopsis']);
			$districts_name='';			
			$districts_name='<div class="quan-huyen">Quận/Huyện:.'.$val['districts_name'].'</div>';			
			$urlOptions = array ('module' => 'article', 'controller' => 'index', 'action' => 'detail', 'cid' => $val ['cat_id'], 'tcat' => $val ['category_alias'], 'title' => $val ['alias'], 'id' => $val ['id'] );
			$linkDetial = $this->url ( $urlOptions, 'article-detail' );

			$created = '';
			if($this->moduleConfig['showDate'] == 1){
				$created = new Zend_Date($val['created'],'dd-MM-YY h:s:i');
				$created = '<span class="date">' . $this->language['articleNgayDang'] . ': ' . $created . '</span>';
			}
			
			$hits = '';
			if($this->moduleConfig['showHits'] == 1){
				$hits = '<span class="hits">' . $this->language['articleXem'] . ': ' . $val['hits'] . '</span>';
			}
		?>
		<div class="item">
			<a href="<?php echo $linkDetial;?>" title="<?php echo $name;?>">
				<?php echo $picture;?>
			</a>
			<div class="desc">
				<h3 class="title">
					<a href="<?php echo $linkDetial;?>" title="<?php echo $name;?>"><?php echo $name;?></a>
				</h3>
				<div>
					<?php echo $created;?>
					<?php echo $hits;?>
				</div>
				<?php echo $districts_name;?>
				<div><?php echo $synopsis;?></div>
				
			</div>
			<div class="readmore">
				<a href="<?php echo $linkDetial;?>"><?php echo $this->language['xemThem']?></a>
			</div>
			<div class="clr"></div>
		</div>
		<?php
			}
		?>

		<?php
			if (empty( $this->arrParam ['keywords'])) {
				$currentUrl = $this->baseUrl ('tim-kiem-nha-dat.html?cat_id='.$this->arrParam ['cat_id'] . '&districts_id=' . $this->arrParam ['districts_id'] );
			} else {
				$currentUrl = $this->baseUrl ('tim-kiem-nha-dat.html?keywords='.$this->arrParam ['keywords'] .'&cat_id='.$this->arrParam ['cat_id'] . '&districts_id=' . $this->arrParam ['districts_id'] );
			}
			echo $this->paginationControl ( $this->paginator, 'Sliding', 'pagination-searchform.phtml', array ('currentUrl' => $currentUrl ) );
		?>
	</div>
	<div class="module_bottom"></div>
</div>
<?php
}else{
	
?>
	<div class="module_article">
		<div class="module_title clearfix">
			<span class="icon"></span> 
			<h1 class="title">Kết quả tìm kiếm</h1>
		</div>
		<div class="module_content line180 pd10">
			Không co kết quả nào được tìm thấy !
		</div>
		<div class="module_bottom"></div>
	</div>
<?php			
} 
?>	


