<div class="module_register">
	<div class="module_content">
		<form action="" method="post" name="frmContact">
			<?php
				// -------------------- SESSAGES ERROR ------------------
				if(count($this->messageError)>0){
					foreach ($this->messageError AS $key => $val){
						echo '<div class="listError" id="'.$key.'" rel="' . $val . '"></div>';
					}
					echo '<div class="infoError">Lỗi: Thông tin bạn nhập còn thiếu hoặc không đúng điều kiện. Vui lòng kiểm tra lại</div>';
				}
			?>
			<div class="info pdt10 pdb10 line180">
				<?php echo $this->blkHtml('default',6);?>
			</div>
			<?php
				$slbNguontin 	= $this->formSelect('nguontin_id',$this->Item['nguontin_id'],array('class' => 'select goc7'),$this->Nguontin) . '<div class="view_error" id="view_nguontin_id"></div>';
				$hoten 			= $this->formText ( 'hoten', $this->Item ['hoten'], array ('class' => 'txtlong goc7' ) ) . '<div class="view_error" id="view_hoten"></div>';
				$diachi 		= $this->formText ( 'diachi', $this->Item ['diachi'], array ('class' => 'txtlong goc7' ) ) . '<div class="view_error" id="view_diachi"></div>';
				$coquan 		= $this->formText ( 'coquan', $this->Item ['coquan'], array ('class' => 'txtlong goc7' ) ) . '<div class="view_error" id="view_coquan"></div>';
				$email 			= $this->formText ( 'email', $this->Item ['email'], array ('class' => 'txtlong goc7' ) ) . '<div class="view_error" id="view_email"></div>';
				$dienthoai 		= $this->formText ( 'dienthoai', $this->Item ['dienthoai'], array ('class' => 'txtlong goc7' ) ) . '<div class="view_error" id="view_dienthoai"></div>';
				$slbThoigian	= $this->formSelect ( 'thoigian_id', $this->Item ['thoigian_id'], array ('class' => 'select goc7' ),$this->Thoigian) . '<div class="view_error" id="view_thoigian_id"></div>';
				$ngayhen 		= $this->formText ( 'ngayhen', $this->Item ['ngayhen'], array ('class' => 'txtmedium goc7', 'id' => 'ngayhen_validate') ) . '<span class="desc">(Ngày/Tháng/Năm)</span><div class="view_error" id="view_ngayhen"></div>';
				$slbKhoahoc		= $this->formSelect ( 'khoahoc_id', $this->Item ['khoahoc_id'], array ('class' => 'select goc7' ),$this->Khoahoc) . '<div class="view_error" id="view_khoahoc_id"></div>';
				$slbTrungtam	= $this->formSelect ( 'trungtam_id', $this->Item ['trungtam_id'], array ('class' => 'select goc7' ),$this->Trungtam) . '<div class="view_error" id="view_trungtam_id"></div>';
				$ngayhoc 		= $this->formText ( 'ngayhoc', $this->Item ['ngayhoc'], array ('class' => 'txtmedium goc7', 'id' => 'ngayhoc_validate') ) . '<span class="desc">(Ngày/Tháng/Năm)</span><div class="view_error" id="view_ngayhoc"></div>';
				$lichhocthichhop= $this->formTextarea ( 'lichhocthichhop', $this->Item ['lichhocthichhop'], array ('rows' => 5, 'cols' => 47,'class' => 'goc7') ) . '<div class="view_error" id="view_lichhocthichhop"></div>';
				$yeucaukhac		= $this->formTextarea ( 'yeucaukhac', $this->Item ['yeucaukhac'], array ('rows' => 5, 'cols' => 47,'class' => 'goc7') ) . '<div class="view_error" id="view_yeucaukhac"></div>';
				
				$captcha = $this->captcha;
				$txtCaptcha = $this->formText ( 'captcha', '', array ('class' => 'txtshort goc7' ) ) . '<div class="view_error" id="view_captcha"></div>';
				$txtID = $this->formHidden ( 'captchaID', $this->captcha_id );
				$lang_code = $this->formHidden ( 'lang', $this->arrParam ['ssFilter'] ['lang_code'] );
				
				$optionNgay = array('00' => 'Ngày','01' => '01','02' => '02','03' => '03','04' => '04','05' => '05','06' => '06','07' => '07','08' => '08','09' => '09');
				for($i = 10; $i <= 31; $i++){
					$optionNgay[$i] = $i;
				}
				$slbNgay = $this->formSelect('ngay',$this->Item['ngay'],array('class' => 'select goc7'),$optionNgay);
				
				$optionThang = array('00' => 'Tháng','01' => '01','02' => '02','03' => '03','04' => '04','05' => '05','06' => '06','07' => '07','08' => '08','09' => '09','10' => '10','11' => '11','12' => '12');
				$slbThang = $this->formSelect('thang',$this->Item['thang'],array('class' => 'select goc7'),$optionThang);
				
				$optionNam = array('0000' => 'Năm');
				for($i = @date('Y') - 80; $i <= @date('Y'); $i++){
					$optionNam[$i] = $i;
				}
				$slbNam = $this->formSelect('nam',$this->Item['nam'],array('class' => 'select goc7'),$optionNam);
			?>
			<div style="padding: 0 0 10px 0; font-size: 14px; font-weight: none; color: #1D5CA2;">
				Bạn vui lòng điền đầy đủ thông tin để được hỗ trợ tốt nhất! Chúc bạn một ngày tốt lành!
			</div>
			<table class="tblContact">
				<tr>
					<td class="label" style="padding-top: 0;">Bạn đã biết đến Langmaster theo nguồn tin nào<span class="red">(*)</span></td>
					<td><?php echo $slbNguontin;?></td>
				</tr>
				<tr>
					<td></td>
					<td><b>Thông tin liên lạc:</b></td>
				</tr>
				<tr>
					<td class="label">Họ và tên<span class="red">(*)</span></td>
					<td><?php echo $hoten;?></td>
				</tr>
				<tr>
					<td class="label">Ngày sinh</td>
					<td><?php echo $slbNgay . ' ' . $slbThang . ' ' . $slbNam;?></td>
				</tr>
				<tr>
					<td class="label">Địa chỉ</td>
					<td><?php echo $diachi;?></td>
				</tr>
				<tr>
					<td class="label">Cơ quan làm việc - Trường học</td>
					<td><?php echo $coquan;?></td>
				</tr>
				<tr>
					<td class="label">Email hay dùng<span class="red">(*)</span></td>
					<td><?php echo $email;?></td>
				</tr>
				<tr>
					<td class="label">Số điện thoại liên lạc<span class="red">(*)</span></td>
					<td><?php echo $dienthoai;?></td>
				</tr>
				<tr>
					<td></td>
					<td><b>Bạn có thể tham gia kiểm tra trình độ vào thời gian nào?:</b></td>
				</tr>
				<tr>
					<td class="label"></td>
					<td><?php echo $slbThoigian;?></td>
				</tr>
				<tr>
					<td class="label">Ngày (ghi cụ thể ngày tháng)<span class="red">(*)</span></td>
					<td><?php echo $ngayhen;?></td>
				</tr>
				<tr>
					<td class="label">Khóa học muốn đăng ký<span class="red">(*)</span></td>
					<td><?php echo $slbKhoahoc;?></td>
				</tr>
				<tr>
					<td class="label">Bạn muốn chọn cơ sở nào<span class="red">(*)</span></td>
					<td><?php echo $slbTrungtam;?></td>
				</tr>
				<tr>
					<td class="label">Khi nào bạn có thể bắt đầu học</td>
					<td><?php echo $ngayhoc;?></td>
				</tr>
				<tr>
					<td class="label">Lịch học thích hợp</td>
					<td><?php echo $lichhocthichhop;?></td>
				</tr>
				<tr>
					<td class="label">Những yêu cầu khác</td>
					<td><?php echo $yeucaukhac;?></td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->language['captcha'];?></td>
					<td><?php echo $txtCaptcha . $txtID . $lang_code;?></td>
				</tr>
				<tr>
					<td></td>
					<td>
						<?php echo $captcha;?>
					</td>
				</tr>
				<tr>
					<td></td>
					<td><?php echo $this->formSubmit('btnSubmit',$this->language['gui'],array('class' => 'goc10 button'));?></td>
				</tr>
			</table>
		</form>
	</div>
	<div class="module_bottom"></div>
	<script type="text/javascript">
	    $(document).ready(function() {
	    	$.datepicker.setDefaults($.datepicker.regional['vi']);
	    	$( "#ngayhen_validate" ).datepicker({
	            changeMonth: true,
	            changeYear: true,
	            minDate: 0,
	            dateFormat: 'dd/mm/yy',
	            monthNamesShort: ['Tháng 01', 'Tháng 02', 'Tháng 03', 'Tháng 04', 'Tháng 05', 'Tháng 06', 'Tháng 07', 'Tháng 08', 'Tháng 09', 'Tháng 10', 'Tháng 11', 'Tháng 12']
	        });
	        $( "#ngayhoc_validate" ).datepicker({
	            changeMonth: true,
	            changeYear: true,
	            minDate: 0,
	            dateFormat: 'dd/mm/yy',
	            monthNamesShort: ['Tháng 01', 'Tháng 02', 'Tháng 03', 'Tháng 04', 'Tháng 05', 'Tháng 06', 'Tháng 07', 'Tháng 08', 'Tháng 09', 'Tháng 10', 'Tháng 11', 'Tháng 12']
	        });
	    });
		$("div.listError").each(function (i) {
		    //alert($(this).attr('rel'));
		    $('#view_' + $(this).attr('id')).html($(this).attr('rel'));
		});
		<?php
		if($_GET['save'] == 'ok'){
			echo "alert('Thông tin của bạn đã được gửi thành công. Langmaster sẽ liên hệ với bạn trong thời gian sớm nhất.')";
		}
		?>
	</script>
	<div style="text-align: right; padding: 20px 0 0px;">
		Được hỗ trợ bởi <a href="#">Phòng công nghệ Langmaster</a> 
	</div>
</div>


