<div class="woocommerce">
<div class="container">
    <section class="sec-cart">
	<div class="cart-header">
		<span class="icon"></span> 
		<h2 class="title"><?php echo $this->language['productGioHang'];?></h2>
	</div>
	<div class="cart-info">
    <div class="row">
	<?php
   
	if($this->arrParam['save'] == 'ok'){
		echo '<div class="note">' . $this->language['sendInfo'] . '</div>';
	}
	if(count($this->Items)){
	?>
		<form name="your-cart" id="your-cart" action="" method="post">
			<div class="cartDetail">
				<table class="shop_table shop_table_responsive cart cart-table" cellspacing="0">
                    <tbody>
					<tr class="title">
						<th><?php echo $this->language['diadiemHinhAnh'];?></th>
						<th><?php echo $this->language['diadiemTenDiaDiem'];?></th>
						<th><?php echo $this->language['diadiemSoLuong'];?></th>
						<th><?php echo $this->language['diadiemGia'] . '('.$this->money['code'].')';?></th>
						<th><?php echo $this->language['diadiemTongTien'] . '('.$this->money['code'].')';?></th>
						<th>Control</th>
					</tr>
					<?php
					$cart = $this->cart;
					if(count($this->Items)){
						$totalPrice = 0;
						foreach ($this->Items as $key => $val){
							$id 		= $val['id'];
							$name 		= $val['name'];
							$price 		= $val['price'];
							$selloff 	= $val['selloff'];
							$units_money = $val['units_money'];
							$quantity	= $cart[$id];
							$picture = '<img class="img" src="' . $val['thumb'] . '" alt="'.$val['name'].'" />';

							$total = 0;
							if($selloff <= 0){
								$total = $quantity * $val['price'];
								$totalPrice += $total;
								$total = Zend_Locale_Format::toNumber($total,array('precision' => 0));
								$price = '<span>'.Zend_Locale_Format::toNumber($price,array('precision' => 0)).'</span>';
								$selloff = '';
							}else{
								$total = $quantity * ($val['price']) - ($val['price'] * ($val['selloff']/100));
								$totalPrice += $total;
								$total = Zend_Locale_Format::toNumber($total,array('precision' => 0));
								$price = '<span style="text-decoration: line-through; color:#666;">'.Zend_Locale_Format::toNumber($price,array('precision' => 0)).'</span>';
								$selloff = Zend_Locale_Format::toNumber(($val['price']) - ($val['price'] * ($val['selloff']/100)),array('precision' => 0)) . '';
							}
							
							$urlOptions = array (
									'module' => 'product',
									'controller' => 'index',
									'action' => 'detail',
									'tcat' => $val ['category_alias'],
									'title' => $val ['alias'],
									'cid' => $val ['cat_id'],
									'id' => $val ['id'] );
							$linkDetial = $this->url( $urlOptions, 'diadiem-detail' );
							
							$itemProduct = 'itemProduct[' . $val['id'] . ']';
							$itemProduct = $this->formText($itemProduct,$quantity,array('style'=>'width: 35px; text-align: center; font-size: 11px; border: 1px solid #CCC;','class'=>'input-text qty text'));
							
					?>
					<tr class="cart_item">
						<td class="product-detail"><?php echo $picture;?></td>
						<td><a href="<?php echo $linkDetial;?>" class="itemLink" target="_blank"><?php echo $name;?></a></td>
						<td class="product-quantity text-center"><div class="quantity-select"><?php echo $itemProduct;?></div></td>
						<td align="center"><?php echo $price . '<br>' . $selloff;?></td>
						<td align="center"><?php echo $total;?></td>
						<td align="center"><a href="<?php echo $this->baseUrl('/product/public/view-cart/delete/'.$id);?>">[Xóa]</a></td>
					</tr>
					<?php
						}
					} 
					?>
					<tr>
						<td colspan="4" align="right"><?php echo $this->language['diadiemTongThanhTien'];?>:</td>
						<td class="price pdl10" colspan="2"><?php echo Zend_Locale_Format::toNumber($totalPrice,array('precision' => 0)) .' '. $this->money['code'];?></td>
					</tr>
					<?php
						$linkOrder =  $this->baseUrl('/product/public/order/');
						$linkBack =  $this->baseUrl('');
					?>
                    </tbody>
				</table>
				<div class="cartDetail-button pdt10">
					<input class="button btn btn-secondary" type="button" name="update" id="update" value="<?php echo $this->language['diadiemDatChoTiep'];?>" class="button goc7" onclick="window.location = '<?php echo $linkBack;?>'" />
					<input class="button btn btn-secondary" type="submit" name="update" id="update" value="<?php echo $this->language['diadiemCapNhatGioHang'];?>" class="button goc7" />
					<input class="button btn btn-secondary" type="button" name="update" id="update" value="<?php echo $this->language['diadiemHoanTatDatHang'];?>" class="button2 goc7" onclick="window.location = '<?php echo $linkOrder;?>'" />
				</div>
			</div>
		</form>
	<?php
	}else{
		echo '<div class="noteCart">' . $this->language['diadiemGioHangRong'] . '</div>';
	} 
	?>
	</div>
    </div>
    </div>
	</section>
</div>