<?php
//die("ads");
	//----------------------- INPUT ELEMENTS -------------------//
	$ssFilter 		= $this->arrParam['ssFilter'];
	$selectLanguages = $ssFilter['lang_code'] . $this->formHidden('lang_code',$ssFilter['lang_code']);
	$name 			= $this->formText ( 'name', $this->Item['name'], array ('class' => 'txtlong active', 'onchange'=>"get_alias()" ) );
	$picture		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture" class="hinh-anh"></div>';
	if(!empty($this->Item['picture'])){
		$picture	= '<div><img src="' . $this->Item['picture'] . '" id="image_picture" class="hinh-anh"></div>';
	}
	$picture 		= $this->cmsUserFiles('picture', $this->Item['picture'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture;
	$option 		= array('Không','Có');
	$status 		= $this->formRadio('status',$this->Item['status'],null,$option, ' ');
	
	if(isset($this->Item['order'])){
		$order = $this->Item['order'];
	}else{
		$order = 255;
	}
	$order 			= $this->formText ('order', $order, array ('class' => 'txtshort' ) );
	$parents		= $this->cmsSelect('parents',$this->Item['parents'],$this->slbCategory,array('style'=>'min-width:200px;'));
	$content 		= $this->cmsEditor('content',htmlspecialchars_decode($this->Item['content']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    $mota 		= $this->formTextarea('mota',$this->Item['mota'],array('rows'=>6,'class' => 'txtlong','style'=>'height:100px'));
    $content_en 		= $this->cmsEditor('content_en',htmlspecialchars_decode($this->Item['content_en']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    $name_en 			= $this->formText ( 'name_en', $this->Item['name_en'], array ('class' => 'txtlong active', 'onchange'=>"get_alias()" ) );
	$mota_en 		= $this->formTextarea('mota_en',$this->Item['mota_en'],array('rows'=>6,'class' => 'txtlong','style'=>'height:100px'));
    
	$arrInput = array(
				array('label' => 'Tiêu đề','input' => $name),
				array('label' => 'Hình ảnh','input' => $picture),
				array('label' => 'Mô tả','input' => $mota),
				array('label' => 'Hiển thị','input' => $status),
				array('label' => 'Thứ tự','input' => $order),
				array('label' => 'Nội dung','input' => $content, 'cols' => 2,'style' => 'padding-top:0;'),
			);
	
	$arrInput_en = array(
				array('label' => 'Tiêu đề','input' => $name_en),
				array('label' => 'Mô tả','input' => $mota_en),
				array('label' => 'Nội dung','input' => $content_en, 'cols' => 2,'style' => 'padding-top:0;'),
			);
	//--------------------- Blocks ---------------------
	$option 			= array('Không','Có');
	if(isset($this->Item['block_left'])){
		$trangthai = $this->Item['block_left'];
	}else{
		$trangthai = 0;
	}
	$blockLeft		= $this->formRadio('block_left',$trangthai,null,$option, ' ');
	
	if(isset($this->Item['block_right'])){
		$trangthai = $this->Item['block_right'];
	}else{
		$trangthai = 0;
	}
	$blockRight			= $this->formRadio('block_right',$trangthai,null,$option, ' ');
	
	if(isset($this->Item['block_body'])){
		$trangthai = $this->Item['block_body'];
	}else{
		$trangthai = 0;
	}
	$blockBody			= $this->formRadio('block_body',$trangthai,null,$option, ' ');
	
	if(isset($this->Item['block_body2'])){
		$trangthai = $this->Item['block_body2'];
	}else{
		$trangthai = 0;
	}
	$blockBody2			= $this->formRadio('block_body2',$trangthai,null,$option, ' ');
	
	$arrBlock = array(
			array('label' => 'Cột trái','input' => $blockLeft),
			array('label' => 'Cột phải','input' => $blockRight),
			array('label' => 'Trang chủ','input' => $blockBody),
			array('label' => 'Trang chủ 2','input' => $blockBody2),
	);
	
	//--------------------- Meta Options ---------------------	
	$alias 				= $this->formText ( 'alias', $this->Item['alias'], array ('class' => 'textlong' ) );
	$tags		 		= $this->formTextarea('tags',$this->Item['tags'],array('rows'=>2,'class' => 'txtalong'));
	$meta_title 		= $this->formTextarea('meta_title',$this->Item['meta_title'],array('rows'=>2,'class' => 'txtalong'));
	$meta_description 	= $this->formTextarea('meta_description',$this->Item['meta_description'],array('rows'=>3,'class' => 'txtalong'));
	$meta_keywords 		= $this->formTextarea('meta_keywords',$this->Item['meta_keywords'],array('rows'=>3,'class' => 'txtalong'));
	
	$arrMeta = array(
			array('label' => 'Liên kết tĩnh','input' => $alias),
			array('label' => 'Meta Title','input' => $meta_title),
			array('label' => 'Meta Description','input' => $meta_description),
			array('label' => 'Meta Keywords','input' => $meta_keywords),
	);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-genex/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php //echo $this->render('admin-genex/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
       
		<div class="width-60 fl">
             <script>
				$(document).ready(function() {
					$(".tabs-nav li:first a").addClass('selected');
					$(".tabs:first").css('display','block');
				    $(".tabs-nav li a").click(function() {
				        $(".tabs-nav li a").removeClass('selected');
				        $(this).addClass('selected');
				        $(".tabs").css('display','none');
				        $($(this).attr("rel")).css('display','block');
				        
				    	return false;
				    });
				});
			</script>
			<ul class="tabs-nav clearfix">
				<li><a rel="#tabs-1" href="javascript:void(0)">Vietnamese</a></li>
				<li><a rel="#tabs-2" href="javascript:void(0)">English</a></li>
				<!--<li><a rel="#tabs-3" href="javascript:void(0)">Thông tin quán</a></li>
				 <li><a rel="#tabs-4" href="javascript:void(0)">Video</a></li> -->
			</ul>
            <fieldset class="adminform tabs" id="tabs-1">
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInput);?>
				</table>
			</fieldset>
			
			<fieldset class="adminform tabs" id="tabs-2">
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInput_en);?>
				</table>
			</fieldset>
			
		</div>
		<div class="width-40 fr">
			<div id="pane-sliders" class="pane-sliders">
				
				<div class="panel">
					<h3 id="metadata-options" class="title pane-toggler-down"><a href="javascript:void(0);"><span>Danh mục thuộc các block</span></a></h3>
					<div class="panel_content">
						<fieldset class="panelform">
							<table class="panelformlist">
								<?php echo $this->partialLoop('row.php', $arrBlock);?>
							</table>
						</fieldset>
					</div>
				</div>
				
				<div class="panel">
					<h3 id="metadata-options" class="title pane-toggler-down"><a href="javascript:void(0);"><span>Metadata Options</span></a></h3>
					<div class="panel_content">
						<fieldset class="panelform">
							<table class="panelformlist">
								<?php echo $this->partialLoop('row.php', $arrMeta);?>
							</table>
						</fieldset>
					</div>
				</div>
					
			</div>
		</div>
		<div class="clr"></div>
	</div>
	<!-- END: 	CONTENT -->
</form>