<?php echo $this->render('html/header.php');?>
	<?php 
		$siteConfig = Zend_Registry::get('siteConfig');
	?>
    <div class="content">
    	<div class=" clearfix">
    		<?php echo $this->blkHeader();?>
    		<?php echo $this->blkMenu('main_menu','main_menu');?>
    		<?php echo $this->blkBreadcrumbs();?>
    		<?php //echo $this->blkAds('slideshow',1);?> 
			<div class="width_wrapper clearfix">
    			<div class="center_content ">
    				 <?php echo $this->layout()->content;?> 
    			</div>
    			<div class="right_content">
    				<?php echo $this->BlkSearchForm();?>
					<?php echo $this->blkAds('right',3);?>
    				<?php echo $this->blkDiadiemLike();?>
    				<?php echo $this->BlkDiadiemHot();?>
    				<?php echo $this->BlkDiadiemMoi();?>
    				<?php echo $this->blkTag('default1');?>
					<?php echo $this->blkHtml('default','4');?>
    			</div>
    			<div class="clear"></div> 
    			 
            </div>
           
            <?php //echo $this->blkMenu('footer_menu','footer_menu');?>
            <?php echo $this->blkFooter();?>
    	</div>
    </div>

<?php echo $this->blkAds('cuon-phai',8);?>
<?php echo $this->blkAds('cuon-trai',7);?>
<?php echo $this->blkAds('goc-phai',9);?>
<script type="text/javascript">
	do_scroll('.block_adsScroll','.scroll_l','.scroll_r');
</script>    
<?php echo $this->render('html/footer.php');?>
