<?php echo $this->render('html/header.php');?>
<body>
	<!-- HEADER -->
    <?php echo $this-> blkHeader($this->category,'unimom'); ?>
     
	
		<div class="clearfix"></div>
        
		
		<div class="aboutus wow swing animated">
			<div class="container">
				<div class="content unimom">
					<h2><a href="">Về UNIMOM</a></h2>
					<?php echo htmlspecialchars_decode($this->category['content']) ; ?>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="sp-doitac wow bounceInUp animated">
			<div class="container">
				<div class="title3">
					<h2><a href="/san-pham/unimom">Sản phẩm</a></h2>
					<div class="line"></div>
				</div>
				<div class="content">
					<div class="sanpham-doitac slider">
					    
                        <?php echo $this->blkSanpham($this->category['manu_id'],3,'unimom'); ?>
				    </div>
				    <script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
				    <script src="<?php echo $this->baseUrl(''); ?>public/templates/public/default/js/slick.js" type="text/javascript" charset="utf-8"></script>
				    <script type="text/javascript">
				    $(document).on('ready', function() {
				      	$('.sanpham-doitac').slick({
						  dots: true,
						  infinite: false,
						  speed: 300,
						  slidesToShow: 3,
						  slidesToScroll: 3,
						  responsive: [
						    {
						      breakpoint: 1024,
						      settings: {
						        slidesToShow: 3,
						        slidesToScroll: 3,
						        infinite: true,
						        dots: true
						      }
						    },
						    {
						      breakpoint: 600,
						      settings: {
						        slidesToShow: 2,
						        slidesToScroll: 2
						      }
						    },
						    {
						      breakpoint: 480,
						      settings: {
						        slidesToShow: 1,
						        slidesToScroll: 1
						      }
						    }
						  ]
						});
				    });
				  </script>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="bantin unimom  wow bounceInUp animated">
			<div class="container">
				<div class="title3">
					<h2><a href="#">Tư vấn</a></h2>
					<div class="line"></div>
				</div>
				<div class="content">
					<div class="row">
						<?php echo $this->blkArticleNoiBat($this->category['manu_id'],3,'unimom') ?>					
					</div>
					<div class="readmore">
						<a href="#">Xem thêm</a>
					</div>
				</div>
			</div>		
		</div>
		<div class="clearfix"></div>
		<div class="bantin unimom  wow bounceInUp animated">
			<div class="container">
				<div class="title3">
					<h2><a href="#">Video</a></h2>
					<div class="line"></div>
				</div>
				<div class="content">
					<div class="row">
						<?php echo $this->blkArticleVideo($this->category['manu_id'],11,3,'unimom'); ?>						
					</div>
					<div class="readmore">
						<a href="">Xem thêm</a>
					</div>
				</div>
			</div>		
		</div>
		<!-- Modal -->
		
		<?php echo $this -> blkDownload(); ?> 
	</main>

	<div class="clearfix"></div>

	<!-- FOOTER -->
    <?php echo $this->blkFooterNew(); ?>
</body>	

</html>


