
<?php /* ?>
<?php echo $this->render('html/header.php');?>
<?php 
	$siteConfig = Zend_Registry::get('siteConfig');
?>
<div class="content">
   	<div class="width_wrapper clearfix">
   		<?php echo $this->blkHeader();?>
   		<?php echo $this->blkMenu('main_menu','main_menu');?>
		<div class="main_content clearfix">
			<div class="module_user">
    			<div class="left_user">
    				<div class="block_cpanel">
    					<div class="block_title">Quản lý tài khoản</div>
    					<div class="block_content">
    						<ul>
    							<li><a href="<?php echo $this->baseUrl('default/user/index')?>" <?php if($this->arrParam['controller'] == 'user' && $this->arrParam['action'] == 'index') echo 'class="selected"';?>>Thông tin tài khoản</a></li>
    							<li><a href="<?php echo $this->baseUrl('default/user/password')?>" <?php if($this->arrParam['controller'] == 'user' && $this->arrParam['action'] == 'password') echo 'class="selected"';?>>Đổi mật khẩu</a></li>
    							<li><a href="<?php echo $this->baseUrl('default/user/article')?>" <?php if($this->arrParam['controller'] == 'user' && $this->arrParam['action'] == 'article') echo 'class="selected"';?>>Bài viết của bạn</a></li>
    							<li><a href="<?php echo $this->baseUrl('default/user/addarticle')?>" <?php if($this->arrParam['controller'] == 'user' && $this->arrParam['action'] == 'article') echo 'class="selected"';?>>Thêm mới bài viết</a></li>
    						</ul>
    					</div>
    				</div>
    			</div>
    			<div class="center_user">
					<?php echo $this->layout()->content;?>
				</div>
				<div class="clr"></div>
			</div>
        </div>
        <?php echo $this->blkMenu('footer_menu','footer_menu');?>
        <?php echo $this->blkFooter();?>
   	</div>
</div>
<?php echo $this->render('html/footer.php');?>
<?php ?> 
<?php */?>
<?php echo $this->render('html/header.php');?>
	<?php 
		$siteConfig = Zend_Registry::get('siteConfig');
	?>
    <div class="content home-content">
    	<div class=" clearfix">
    		<?php echo $this->blkHeader();?>
    		<?php echo $this->blkMenu('main_menu','main_menu');?>
    		<?php echo $this->blkBreadcrumbs();?>
			<div class="width_wrapper clearfix">
    		 	<div class="main_content clearfix">
						<div class="module_user">
			    			<div class="left_user">
			    				<div class="block_cpanel">
			    					<div class="block_title">Quản lý tài khoản</div>
			    					<div class="block_content">
			    						<ul>
			    							<li><a href="<?php echo $this->baseUrl('member.html')?>" <?php if($this->arrParam['controller'] == 'user' && $this->arrParam['action'] == 'index') echo 'class="selected"';?>>Thông tin tài khoản</a></li>
			    							<li><a href="<?php echo $this->baseUrl('password.html')?>" <?php if($this->arrParam['controller'] == 'user' && $this->arrParam['action'] == 'password') echo 'class="selected"';?>>Đổi mật khẩu</a></li>
			    							<li><a href="<?php echo $this->baseUrl('member-article.html')?>" <?php if($this->arrParam['controller'] == 'user' && $this->arrParam['action'] == 'article') echo 'class="selected"';?>>Bài viết của bạn</a></li>
			    							<li><a href="<?php echo $this->baseUrl('add-article.html')?>" <?php if($this->arrParam['controller'] == 'user' && $this->arrParam['action'] == 'addarticle') echo 'class="selected"';?>>Thêm mới bài viết</a></li>
			    						</ul>
			    					</div>
			    				</div>
			    			</div>
			    			<div class="center_user">
								<?php echo $this->layout()->content;?>
							</div>
							<div class="clr"></div>
						</div>
			        </div>
            </div>
            <?php //echo $this->blkAds('doi-tac',4);?>
            <?php //echo $this->blkMenu('footer_menu','footer_menu');?>
            <?php echo $this->blkFooter();?>
    	</div>
    </div>

<?php echo $this->blkAds('cuon-phai',8);?>
<?php echo $this->blkAds('cuon-trai',7);?>
<?php echo $this->blkAds('goc-phai',9);?>
<script type="text/javascript">
	do_scroll('.block_adsScroll','.scroll_l','.scroll_r');
</script>    
<?php echo $this->render('html/footer.php');?>



