

<?php echo $this->render('html/header.php');?>
	<?php 
		$siteConfig = Zend_Registry::get('siteConfig');
	?>
    <div class="content home-content">
    	<div class=" clearfix">
    		<?php echo $this->blkHeader();?>
    		<?php echo $this->blkMenu('main_menu','main_menu');?>
    		<?php echo $this->blkBreadcrumbs();?>
			<div class="width_wrapper clearfix">
    		 	<?php echo $this->layout()->content;?>
            </div>
            <?php //echo $this->blkAds('doi-tac',4);?>
            <?php //echo $this->blkMenu('footer_menu','footer_menu');?>
            <?php echo $this->blkFooter();?>
    	</div>
    </div>

<?php echo $this->blkAds('cuon-phai',8);?>
<?php echo $this->blkAds('cuon-trai',7);?>
<?php echo $this->blkAds('goc-phai',9);?>
<script type="text/javascript">
	do_scroll('.block_adsScroll','.scroll_l','.scroll_r');
</script>    
<?php echo $this->render('html/footer.php');?>


