<script type="text/javascript" src="/diachianchoi/public/templates/public/default/js/waypoints.js"></script>
<script type="text/javascript" src="/diachianchoi/public/templates/public/default/js/jquery_0061.js"></script>
<section class="banner">
    <div style="background-color:#F2F3F5;">
        <div class="container">
            <img width="100%" alt="" src="/public/files/editor-upload/images/demo/client.jpg">
        </div>
    </div>
</section>


<div id="main">
  <div class="container">
    <article>
      <h1 class="breadcrumb">Giới thiệu</h1>
      <script type="text/javascript">
	jQuery(document).ready(function( $ ) {
	    $('.counter').counterUp({
	        delay: 10,
	        time: 1000
	    });
	});
</script>
<div class="row">
	<div class="col-sm-3 text-justify">
		<h2>Chúng tôi là ai?</h2>
		<p>Sao Kim là công ty chuyên sâu về hoạch định chiến lược, thiết kế 
nhận diện và truyền thông thương hiệu. Chúng tôi cung cấp một giải pháp 
toàn diện giúp doanh nghiệp nâng cao năng lực cạnh tranh thông qua việc 
xây dựng thương hiệu mạnh.</p>

		<p>Sao Kim tự hào đang tạo ra sức mạnh và sinh khí cho hàng nghìn 
thương hiệu khách hàng qua đó nỗ lực góp sức mình vào sứ mệnh vì sự 
phát triển của thương hiệu Việt.</p>

		<p>Chúng tôi luôn giao tiếp cởi mở và lắng nghe yêu cầu của khách hàng
 để có thể đảm bảo thấu hiểu yêu cầu sáng tạo ngay từ khi mới bắt đầu và
 đảm bảo tính nhất quán trong suốt quá trình thực thi dự án.  
		Cam kết mang lại những giải pháp sáng tạo và hiệu quả, Sao Kim đồng 
hành cùng doanh nghiệp xây dựng thương hiệu mạnh.</p>

		<h2>Vì sao chọn chúng tôi?</h2>


		<div class="counter-item">
			<div class="counter-number"><span class="counter">2000</span> +</div>
			<div class="counter-text">Khách hàng tin tưởng</div>
		</div>
		<div class="counter-item">
			<div class="counter-number"><span class="counter">6800</span>+</div>
			<div class="counter-text">Dự án đã hoàn thành</div>
		</div>
		<div class="counter-item">
			<div class="counter-number"><span class="counter">40</span>+</div>
			<div class="counter-text">Nhân sự tài năng</div>
		</div>
		<div class="counter-item">
			<div class="counter-number"><span class="counter">8</span>+</div>
			<div class="counter-text">Năm kinh nghiệm</div>
		</div>
	</div>
	<div class="col-sm-6">
		<h2>Chúng tôi làm gì?</h2>
		<div class="progress icon1">
			<div class="progress-content">
				<h3>Nghiên cứu</h3>
				<h4>Nghiên cứu nội tại</h4>
				<ul>
					<li><a href="#">Tài liệu maketing, ấn phẩm, báo cáo thường niên, website...</a></li>
					<li><a href="#">Trao đổi với lãnh đạo doanh nghiệp</a></li>
				</ul>
				<h4>Nghiên cứu thị trường</h4>
				<ul>
					<li><a href="#">Cản nhận của khách hàng về thương hiệu</a></li>
					<li><a href="#">Các thương hiệu cạnh tranh</a></li>
				</ul>
			</div>
		</div>
		<div class="progress icon3">
			<div class="progress-content">
				<h3>Chiến lược thương hiệu</h3>
				<ul>
					<li><a href="#">Xây dựng chiến lược thương hiệu</a></li>
					<li><a href="#">Xác lập định vị thương hiệu</a></li>
					<li><a href="#">Quy chuẩn kiến trúc thương hiệu</a></li>
				</ul>
			</div>
		</div>
		<div class="progress icon2">
			<div class="progress-content">
				<h3>Hệ thống nhận diện thương hiệu</h3>
				<h4>Nhận diện doanh nghiệp</h4>
				<h4>Nhận diện cốt lõi</h4>
				<ul>
					<li><a href="#">Brandname, subrand name</a></li>
					<li><a href="#">Logo, slogan, logo subbrand, logo guidelines</a></li>
				</ul>
				<h4>Tài liệu marketing - bán hàng</h4>
				<ul>
					<li><a href="#">Sales &amp; Marketing tools</a></li>
					<li><a href="#">Print ads: Brochure, flyer, poster</a></li>
					<li><a href="#">Multimedia: E - catalogue, TVC</a></li>
				</ul>
				<h4>Nhận diện tại cửa hàng</h4>
				<ul>
					<li><a href="#">Posm</a></li>
					<li><a href="#">Biển bảng</a></li>
					<li><a href="#">Print Ads</a></li>
				</ul>
				<h4>Nhận diện cho người tiêu dùng</h4>
				<h4>Chiến dịch marketing</h4>
				<ul>
					<li><a href="#">Direct marketing: mail, email SMS, newsletter v.v...</a></li>
					<li><a href="#">Event: tradshow, event</a></li>
					<li><a href="#">Advertising: Billboard, Online radio, Television</a></li>
				</ul>
			</div>
		</div>

		<div class="progress icon4">
			<div class="progress-content">
				<h3>Truyền thông thương hiệu</h3>
				<ul>
					<li><a href="#">Giới thiệu nhận diện thương hiệu mới</a></li>
					<li><a href="#">Kế hoạch truyền thông</a></li>
					<li><a href="#">Kích hoạt thương hiệu mới</a></li>
				</ul>
			</div>
		</div>

		<div class="progress icon5">
			<div class="progress-content">
				<h3>Quản trị thương hiệu</h3>
				<ul>
					<li><a href="#">Đào tạo nội bộ</a></li>
					<li><a href="#">Giới thiệu nhận diện thương hiệu</a></li>
					<li><a href="#">Cẩm nang hướng dẫn</a></li>
				</ul>
			</div>
		</div>

	</div>
	<div class="col-sm-3" id="sidebar-about">
		<div id="about_slider-2" class="widget widget_about_slider widget-1 widget-first "><h2 class="widget-title">Tin tức hoạt động</h2>	

		<script type="text/javascript">
			jQuery(document).ready(function() {
		      var slider_833256782 = jQuery("#post-slider-833256782");
		      	slider_833256782.owlCarousel({
		        items : 1, //3 items above 1000px browser width
		        itemsDesktop : [1170,1], //5 items between 1000px and 901px
		        itemsDesktopSmall : [900,1], // 3 items betweem 900px and 601px
		        itemsTablet: [600,1], //2 items between 600 and 0;
		        itemsMobile : [480,1], // itemsMobile disabled - inherit from itemsTablet option
		        autoPlay: true,
		        pagination:false,
		      });

		      		  	});
		</script>
		</div><div id="text-7" class="widget widget_text widget-2 ">			<div class="textwidget"><div style="margin-bottom:2px;">
      <a href="#" class="btn-plus">Gửi Portfolio / CV</a>
</div></div>
		</div><div id="text-6" class="widget widget_text widget-3 widget-last ">			<div class="textwidget"><div role="form" class="wpcf7" id="wpcf7-f126-p2-o1" dir="ltr" lang="vi">
<div class="screen-reader-response"></div>
<form action="/gioi-thieu/#wpcf7-f126-p2-o1" method="post" class="wpcf7-form" enctype="multipart/form-data" novalidate="novalidate">
<div style="display: none;">
<input name="_wpcf7" value="126" type="hidden">
<input name="_wpcf7_version" value="4.2.2" type="hidden">
<input name="_wpcf7_locale" value="vi" type="hidden">
<input name="_wpcf7_unit_tag" value="wpcf7-f126-p2-o1" type="hidden">
<input name="_wpnonce" value="fbc74cb487" type="hidden">
</div>
<div class="sidebarform">
<a class="hotline" href="tel:+84964699499"><span class="icon"></span>Hotline <br> <span class="number">0964.699.499</span></a>
<div class="form">
<p><span class="wpcf7-form-control-wrap your-name"><input name="your-name" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="Họ tên *" type="text"></span></p>
<p><span class="wpcf7-form-control-wrap your-email"><input name="your-email" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false" placeholder="Email *" type="email"></span></p>
<p><span class="wpcf7-form-control-wrap your-phone"><input name="your-phone" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="Số điện thoại *" type="text"></span></p>
<p><span class="wpcf7-form-control-wrap your-address"><input name="your-address" size="40" class="wpcf7-form-control wpcf7-text" aria-invalid="false" placeholder="Địa chỉ *" type="text"></span></p>
<p><span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="Lý do bạn muốn gia nhập cùng chúng tôi?"></textarea></span></p>
<p>Vị trí ứng tuyển  * <br> <span class="wpcf7-form-control-wrap your-position"><select name="your-position" class="wpcf7-form-control wpcf7-select wpcf7-validates-as-required" aria-required="true" aria-invalid="false"><option selected="selected" value="">---</option><option value="Creative Designer">Creative Designer</option><option value="Account Executive">Account Executive</option><option value="Account Manager">Account Manager</option><option value="Sales Admin">Sales Admin</option><option value="Copywriter">Copywriter</option><option value="Brand Strategist">Brand Strategist</option><option value="Communication Planner">Communication Planner</option><option value="Photographer">Photographer</option><option value="Internship">Internship</option><option value="Other Position">Other Position</option></select></span></p>
<p>Ứng tuyển tại văn phòng  *<br><span class="wpcf7-form-control-wrap region"><select name="region" class="wpcf7-form-control wpcf7-select wpcf7-validates-as-required" id="region" aria-required="true" aria-invalid="false"><option selected="selected" value="">---</option><option value="Hà Nội">Hà Nội</option><option value="TP. Hồ Chí Minh">TP. Hồ Chí Minh</option></select></span></p>
<p><strong>CV &amp; Portfolio  *:</strong> <br>Send us your CV or portfolio<br> (5mb .doc or .pdf or zip/rar)</p>
<p><span class="wpcf7-form-control-wrap your-cv"><input name="your-cv" value="1" size="40" class="wpcf7-form-control wpcf7-file wpcf7-validates-as-required" aria-required="true" aria-invalid="false" type="file"></span></p>
<p class="text-right"><input name="referer" value="http://www.saokim.com.vn/gioi-thieu/" type="hidden"> <input value="Nộp hồ sơ" class="wpcf7-form-control wpcf7-submit" type="submit"><img style="visibility: hidden;" alt="Sending ..." src="index_files/ajax-loader.gif" class="ajax-loader"></p>

</div>
</div></form>
<div class="wpcf7-response-output wpcf7-display-none"></div></div></div>
		</div>	</div>
	<div class="clearfix"></div>
</div>

    </article>
  </div>
</div>