<?php
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-link/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php //echo $this->render('admin-link/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
        <div class="width-50 fl">
		<fieldset class="adminform">
			<legend>PC</legend>
				<ul class="adminformlist" id="imagelist">
					<?php
					$numberImage = 0;
					if($this->Item['picture_multi'] != ''){
						$this->Item['picture_multi'] = unserialize($this->Item['picture_multi']);
					}else{
						$this->Item['picture_multi'] = array();
					}
					if(count($this->Item['picture_multi']) > 0){
						$numberImage = count($this->Item['picture_multi']);
						foreach($this->Item['picture_multi'] AS $key => $val){
				?>
					<li id="picture<?php echo $key;?>">
						<script type="text/javascript">
						function openKCFinder<?php echo $key;?>(field) {
							$('#formLoading').removeClass().addClass('loading').fadeIn();
							window.KCFinder = {
								callBack: function(url) {
									field.value = url;
									window.KCFinder = null;
									document.getElementById('image_picture_multi<?php echo $key;?>').src = url;
								}
							};
							window.open('<?php echo SCIPTS_URL . '/media_files/browse.php?type=images&lng=vi';?>', 'kcfinder_textbox','status=0, toolbar=0, location=0, menubar=0, directories=0,resizable=1, scrollbars=0, width=950, height=450' );
							$('#formLoading').removeClass().fadeOut();
						}</script>
						<div>
							<input value="<?php echo $val[0];?>" type="text" name="picture_multi[]" id="picture_multi<?php echo $key;?>" class="txtfile"><a href="javascript:void(0);" onclick="openKCFinder<?php echo $key;?>(appForm.picture_multi<?php echo $key;?>)" class="btnMedia">Chọn ảnh</a><span class="pdl20">Thứ tự <input type="text" name="orderImage[]" style="width: 50px;" value="<?php echo $val[1];?>"></span><span class="pdl20"><a href="javascript:void(0);" onclick="javascript:Delete(<?php echo $key;?>);">[Xóa]</a></span>
						</div>
						<div><img src="<?php echo $val[0];?>" style="width: 60px;" id="image_picture_multi<?php echo $key;?>"></div>
						<div class="clr"></div>
					</li>
					<?php
						}
					} 
					?>
				</ul>
				<div class="fr">
					<a href="javascript:void(0);" onclick="creatImage()" class="btnMedia">Thêm ảnh</a>
				</div>
				<input type="hidden" name="numberImage" id="numberImage" value="<?php echo $numberImage;?>">
				<script type="text/javascript">
					function creatImage(){
						//alert('hic');
						var picture = '<li id="picture{i}">'+
							'<script type="text/javascript">'+
							'function openKCFinder{i}(field) {'+
								'$(\'#formLoading\').removeClass().addClass(\'loading\').fadeIn();'+
								'window.KCFinder = {'+
									'callBack: function(url) {'+
										'field.value = url;'+
										'window.KCFinder = null;'+
										'document.getElementById(\'image_picture_multi{i}\').src = url;'+
									'}'+
								'};'+
								'window.open(\'<?php echo SCIPTS_URL . '/media_files/browse.php?type=images&lng=vi';?>\', \'kcfinder_textbox\',\'status=0, toolbar=0, location=0, menubar=0, directories=0,resizable=1, scrollbars=0, width=950, height=450\');'+
								'$(\'#formLoading\').removeClass().fadeOut();'+
							'}<\/script>'+
							'<div>'+
								'<input value="" type="text" name="picture_multi[]" id="picture_multi{i}" class="txtfile">'+
								'<a href="javascript:void(0);" onclick="openKCFinder{i}(appForm.picture_multi{i})" class="btnMedia">Chọn ảnh</a>'+
								'<span class="pdl20">Thứ tự <input type="text" name="orderImage[]" style="width: 50px;" value="0"></span>'+
								'<span class="pdl20">'+
									'<a href="javascript:void(0);" onclick="javascript:Delete({i});">[Xóa]</a>'+
								'</span>'+
							'</div>'+
							'<div class="clr"></div>'+
							'<div><img src="<?php echo $this->imgUrl . '/no-avatar.png';?>" id="image_picture_multi{i}" class="hinh-anh" style="width: 60px;"></div>'+
						'</li>';
						var i = parseInt($('#numberImage').val());
						var str = picture;
						str = str.replace(/{i}/gi,i);
						str = str.replace(/{i2}/gi,i+1);
						$('#imagelist').append(str);
						$('#numberImage').val(i+1);
					}
					function Delete(i) {
						$('#picture'+i).remove();
					}
				</script>
		
		</fieldset>
        </div>
        <div class="width-50 fl">
		<fieldset class="adminform">
			<legend>Mobile</legend>
				<ul class="adminformlist" id="imagelistMobile">
					<?php
					$numberImage = 0;
					if($this->Item['picture_multi_mobile'] != ''){
						$this->Item['picture_multi_mobile'] = unserialize($this->Item['picture_multi_mobile']);
					}else{
						$this->Item['picture_multi_mobile'] = array();
					}
					if(count($this->Item['picture_multi_mobile']) > 0){
						$numberImage = count($this->Item['picture_multi_mobile']);
						foreach($this->Item['picture_multi_mobile'] AS $key => $val){
				?>
					<li id="picture_mobile<?php echo $key;?>">
						<script type="text/javascript">
						function openKCFinder<?php echo $key;?>(field) {
							$('#formLoading').removeClass().addClass('loading').fadeIn();
							window.KCFinder = {
								callBack: function(url) {
									field.value = url;
									window.KCFinder = null;
									document.getElementById('image_picture_multi_mobile<?php echo $key;?>').src = url;
								}
							};
							window.open('<?php echo SCIPTS_URL . '/media_files/browse.php?type=images&lng=vi';?>', 'kcfinder_textbox','status=0, toolbar=0, location=0, menubar=0, directories=0,resizable=1, scrollbars=0, width=950, height=450' );
							$('#formLoading').removeClass().fadeOut();
						}</script>
						<div>
							<input value="<?php echo $val[0];?>" type="text" name="picture_multi_mobile[]" id="picture_multi_mobile<?php echo $key;?>" class="txtfile"><a href="javascript:void(0);" onclick="openKCFinder<?php echo $key;?>(appForm.picture_multi_mobile<?php echo $key;?>)" class="btnMedia">Chọn ảnh</a><span class="pdl20">Thứ tự <input type="text" name="orderImage[]" style="width: 50px;" value="<?php echo $val[1];?>"></span><span class="pdl20"><a href="javascript:void(0);" onclick="javascript:Delete(<?php echo $key;?>);">[Xóa]</a></span>
						</div>
						<div><img src="<?php echo $val[0];?>" style="width: 60px;" id="image_picture_multi_mobile<?php echo $key;?>"></div>
						<div class="clr"></div>
					</li>
					<?php
						}
					} 
					?>
				</ul>
				<div class="fr">
					<a href="javascript:void(0);" onclick="creatImageMobile()" class="btnMedia">Thêm ảnh</a>
				</div>
				<input type="hidden" name="numberImage" id="numberImage" value="<?php echo $numberImage;?>">
				<script type="text/javascript">
					function creatImageMobile(){
						//alert('hic');
						var picture = '<li id="picture_mobile{i}">'+
							'<script type="text/javascript">'+
							'function openKCFinder{i}(field) {'+
								'$(\'#formLoading\').removeClass().addClass(\'loading\').fadeIn();'+
								'window.KCFinder = {'+
									'callBack: function(url) {'+
										'field.value = url;'+
										'window.KCFinder = null;'+
										'document.getElementById(\'image_picture_multi_mobile{i}\').src = url;'+
									'}'+
								'};'+
								'window.open(\'<?php echo SCIPTS_URL . '/media_files/browse.php?type=images&lng=vi';?>\', \'kcfinder_textbox\',\'status=0, toolbar=0, location=0, menubar=0, directories=0,resizable=1, scrollbars=0, width=950, height=450\');'+
								'$(\'#formLoading\').removeClass().fadeOut();'+
							'}<\/script>'+
							'<div>'+
								'<input value="" type="text" name="picture_multi_mobile[]" id="picture_multi_mobile{i}" class="txtfile">'+
								'<a href="javascript:void(0);" onclick="openKCFinder{i}(appForm.picture_multi_mobile{i})" class="btnMedia">Chọn ảnh</a>'+
								'<span class="pdl20">Thứ tự <input type="text" name="orderImage[]" style="width: 50px;" value="0"></span>'+
								'<span class="pdl20">'+
									'<a href="javascript:void(0);" onclick="javascript:Delete({i});">[Xóa]</a>'+
								'</span>'+
							'</div>'+
							'<div class="clr"></div>'+
							'<div><img src="<?php echo $this->imgUrl . '/no-avatar.png';?>" id="image_picture_multi_mobile{i}" class="hinh-anh" style="width: 60px;"></div>'+
						'</li>';
						var i = parseInt($('#numberImage').val());
						var str = picture;
						str = str.replace(/{i}/gi,i);
						str = str.replace(/{i2}/gi,i+1);
						$('#imagelistMobile').append(str);
						$('#numberImage').val(i+1);
					}
					function Delete(i) {
						$('#picture'+i).remove();
					}
				</script>
		
		</fieldset>
        </div>
	</div>
	<!-- END: 	CONTENT -->
</form>