<?php
//die("ads");
	//----------------------- INPUT ELEMENTS -------------------//
	$ssFilter 		= $this->arrParam['ssFilter'];
	$selectLanguages = $ssFilter['lang_code'] . $this->formHidden('lang_code',$ssFilter['lang_code']);
	$name 			= $this->formText ( 'name', $this->Item['name'], array ('class' => 'txtlong active', 'onchange'=>"get_alias()" ) );
	$picture		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture" class="hinh-anh"></div>';
	if(!empty($this->Item['picture'])){
		$picture	= '<div><img src="' . $this->Item['picture'] . '" id="image_picture" class="hinh-anh"></div>';
	}
	$picture 		= $this->cmsUserFiles('picture', $this->Item['picture'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture;
    
    $picture_mobile		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture_mobile" class="hinh-anh"></div>';
	if(!empty($this->Item['picture_mobile'])){
		$picture_mobile	= '<div><img src="' . $this->Item['picture_mobile'] . '" id="image_picture_mobile" class="hinh-anh"></div>';
	}
	$picture_mobile 		= $this->cmsUserFiles('picture_mobile', $this->Item['picture_mobile'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture_mobile;
    
    
    
    $picture_vitri		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture_vitri" class="hinh-anh"></div>';
	if(!empty($this->Item['picture_vitri'])){
		$picture_vitri	= '<div><img src="' . $this->Item['picture_vitri'] . '" id="image_picture_vitri" class="hinh-anh"></div>';
	}
	$picture_vitri 		= $this->cmsUserFiles('picture_vitri', $this->Item['picture_vitri'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture_vitri;
    
    
	$option 		= array('Không','Có');
	$status 		= $this->formRadio('status',$this->Item['status'],null,$option, ' ');
	
	if(isset($this->Item['order'])){
		$order = $this->Item['order'];
	}else{
		$order = 255;
	}
	$order 			= $this->formText ('order', $order, array ('class' => 'txtshort' ) );
	$parents		= $this->cmsSelect('parents',$this->Item['parents'],$this->slbCategory,array('style'=>'min-width:200px;'));
	$content 		= $this->cmsEditor('content',htmlspecialchars_decode($this->Item['content']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    $content1 		= $this->cmsEditor('content_en',htmlspecialchars_decode($this->Item['content_en']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
	$mota 		= $this->formTextarea('mota',$this->Item['mota'],array('rows'=>6,'class' => 'txtlong','style'=>'height:100px'));
    $mota_en 		= $this->formTextarea('mota_en',$this->Item['mota_en'],array('rows'=>6,'class' => 'txtlong','style'=>'height:100px'));
	$arrInput = array(
				//array('label' => 'Chọn ngôn ngữ','input' => $selectLanguages),
				array('label' => 'Tiêu đề','input' => $name),
				array('label' => 'Hình ảnh Banner PC','input' => $picture),
                array('label' => 'Hình ảnh Banner Mobile','input' => $picture_mobile),
				array('label' => 'Mô tả','input' => $mota),
                array('label' => 'Hình ảnh vị trí','input' => $picture_vitri),
				array('label' => 'Nội dung','input' => $content, 'cols' => 2,'style' => 'padding-top:0;'),
			);
	
	$arrInputEn = array(
				
				array('label' => 'Mô tả','input' => $mota_en),
				array('label' => 'Nội dung','input' => $content1, 'cols' => 2,'style' => 'padding-top:0;'),
			);
	//--------------------- Blocks ---------------------
	$option 			= array('Không','Có');
	if(isset($this->Item['block_left'])){
		$trangthai = $this->Item['block_left'];
	}else{
		$trangthai = 0;
	}
	$blockLeft		= $this->formRadio('block_left',$trangthai,null,$option, ' ');
	
	if(isset($this->Item['block_right'])){
		$trangthai = $this->Item['block_right'];
	}else{
		$trangthai = 0;
	}
	$blockRight			= $this->formRadio('block_right',$trangthai,null,$option, ' ');
	
	if(isset($this->Item['block_body'])){
		$trangthai = $this->Item['block_body'];
	}else{
		$trangthai = 0;
	}
	$blockBody			= $this->formRadio('block_body',$trangthai,null,$option, ' ');
	
	if(isset($this->Item['block_body2'])){
		$trangthai = $this->Item['block_body2'];
	}else{
		$trangthai = 0;
	}
	$blockBody2			= $this->formRadio('block_body2',$trangthai,null,$option, ' ');
	
	$arrBlock = array(
			array('label' => 'Cột trái','input' => $blockLeft),
			array('label' => 'Cột phải','input' => $blockRight),
			array('label' => 'Trang chủ','input' => $blockBody),
			array('label' => 'Trang chủ 2','input' => $blockBody2),
	);
	
	//--------------------- Meta Options ---------------------	
	$alias 				= $this->formText ( 'alias', $this->Item['alias'], array ('class' => 'textlong' ) );
	$tags		 		= $this->formTextarea('tags',$this->Item['tags'],array('rows'=>2,'class' => 'txtalong'));
	$meta_title 		= $this->formTextarea('meta_title',$this->Item['meta_title'],array('rows'=>2,'class' => 'txtalong'));
	$meta_description 	= $this->formTextarea('meta_description',$this->Item['meta_description'],array('rows'=>3,'class' => 'txtalong'));
	$meta_keywords 		= $this->formTextarea('meta_keywords',$this->Item['meta_keywords'],array('rows'=>3,'class' => 'txtalong'));
	
	$arrMeta = array(
			array('label' => 'Liên kết tĩnh','input' => $alias),
			array('label' => 'Meta Title','input' => $meta_title),
			array('label' => 'Meta Description','input' => $meta_description),
			array('label' => 'Meta Keywords','input' => $meta_keywords),
	);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-genex/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php //echo $this->render('admin-genex/sublink/index.php');?>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<div class="width-50 fl">
			<fieldset class="adminform">
				<legend>Vietnamese</legend>
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInput);?>
				</table>
			</fieldset>
		</div>
        <div class="width-50 fr">
			<fieldset class="adminform">
				<legend>English</legend>
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInputEn);?>
				</table>
			</fieldset>
		</div>
		
		<div class="clr"></div>
	</div>
	<!-- END: 	CONTENT -->
</form>