<?php
//die("ads");
	//----------------------- INPUT ELEMENTS -------------------//
	$ssFilter 		= $this->arrParam['ssFilter'];
	$selectLanguages = $ssFilter['lang_code'] . $this->formHidden('lang_code',$ssFilter['lang_code']);
	$name 			= $this->formText ( 'name', $this->Item['name'], array ('class' => 'txtlong active', 'onchange'=>"get_alias()" ) );
	$picture		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture" class="hinh-anh"></div>';
	if(!empty($this->Item['picture'])){
		$picture	= '<div><img src="' . $this->Item['picture'] . '" id="image_picture" class="hinh-anh"></div>';
	}
	$picture 		= $this->cmsUserFiles('picture', $this->Item['picture'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture;
    
    $picture_mobile		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture_mobile" class="hinh-anh"></div>';
	if(!empty($this->Item['picture_mobile'])){
		$picture_mobile	= '<div><img src="' . $this->Item['picture_mobile'] . '" id="image_picture_mobile" class="hinh-anh"></div>';
	}
	$picture_mobile 		= $this->cmsUserFiles('picture_mobile', $this->Item['picture_mobile'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture_mobile;
    
    
    $picture_tongquan		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_image_tongquan" class="hinh-anh"></div>';
	if(!empty($this->Item['image_tongquan'])){
		$picture_tongquan	= '<div><img src="' . $this->Item['image_tongquan'] . '" id="image_image_tongquan" class="hinh-anh"></div>';
	}
	$picture_tongquan 		= $this->cmsUserFiles('image_tongquan', $this->Item['image_tongquan'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture_tongquan;
    
    
    
    $picture_solieu		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_image_solieu" class="hinh-anh"></div>';
	if(!empty($this->Item['image_solieu'])){
		$picture_solieu	= '<div><img src="' . $this->Item['image_solieu'] . '" id="image_image_solieu" class="hinh-anh"></div>';
	}
	$picture_solieu 		= $this->cmsUserFiles('image_solieu', $this->Item['image_solieu'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture_solieu;
    
    
	$option 		= array('Không','Có');
	$status 		= $this->formRadio('status',$this->Item['status'],null,$option, ' ');
	
	if(isset($this->Item['order'])){
		$order = $this->Item['order'];
	}else{
		$order = 255;
	}
	$order 			= $this->formText ('order', $order, array ('class' => 'txtshort' ) );
	$parents		= $this->cmsSelect('parents',$this->Item['parents'],$this->slbCategory,array('style'=>'min-width:200px;'));
	
	
    $content 		= $this->cmsEditor('content',htmlspecialchars_decode($this->Item['content']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    $content1 		= $this->cmsEditor('content_en',htmlspecialchars_decode($this->Item['content_en']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    $mota 		    = $this->cmsEditor('mota',htmlspecialchars_decode($this->Item['mota']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    $mota_en 		= $this->cmsEditor('mota_en',htmlspecialchars_decode($this->Item['mota_en']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    $vitri_content 	= $this->cmsEditor('vitri_content',htmlspecialchars_decode($this->Item['vitri_content']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    $vitri_content_en = $this->cmsEditor('vitri_content_en',htmlspecialchars_decode($this->Item['vitri_content_en']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    
    $tongdientich 			= $this->formText ( 'dientich', $this->Item['dientich'], array ('class' => 'txtlong') );
    $matdo 			= $this->formText ( 'matdo', $this->Item['matdo'], array ('class' => 'txtlong') );
    $dtcayxanh 			= $this->formText ( 'dtcayxanh', $this->Item['dtcayxanh'], array ('class' => 'txtlong') );
    $dtgiaothong 			= $this->formText ( 'dtgiaothong', $this->Item['dtgiaothong'], array ('class' => 'txtlong') );
    $noidung_image_tongquan 		=$this->cmsEditor('noidung_image_tongquan',htmlspecialchars_decode($this->Item['noidung_image_tongquan']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    $noidung_image_tongquan_en 		= $this->cmsEditor('noidung_image_tongquan_en',htmlspecialchars_decode($this->Item['noidung_image_tongquan_en']),array('toolbar'=>'MyToolbar', 'language'=>'vi'));
    
	$arrInput = array(
				//array('label' => 'Chọn ngôn ngữ','input' => $selectLanguages),
				array('label' => 'Tiêu đề','input' => $name),
				array('label' => 'Hình ảnh Banner PC','input' => $picture),
                array('label' => 'Hình ảnh Banner Mobile','input' => $picture_mobile),    
                array('label' => 'Hình ảnh tổng quan','input' => $picture_tongquan),
                array('label' => 'Background số liệu','input' => $picture_solieu),
                array('label' => 'Giới thiệu ngắn','input' => $content,'cols' => 2,'style' => 'padding-top:0;'),
				array('label' => 'Mô tả','input' => $mota,'cols' => 2,'style' => 'padding-top:0;'),
                array('label' => 'Nội dung vị trí ','input' => $vitri_content, 'cols' => 2,'style' => 'padding-top:0;'),
                array('label' => 'Nội dung hình ảnh tổng quan','input' => $noidung_image_tongquan,'cols' => 2,'style' => 'padding-top:0;'),
                
			);
	
	$arrInputEn = array(
				array('label' => 'Giới thiệu ngắn','input' => $content1,'cols' => 2,'style' => 'padding-top:0;'),
				array('label' => 'Mô tả','input' => $mota_en,'cols' => 2,'style' => 'padding-top:0;'),
				array('label' => 'Nội dung vị trí ','input' => $vitri_content_en, 'cols' => 2,'style' => 'padding-top:0;'),
                array('label' => 'Nội dung hình ảnh tổng quan','input' => $noidung_image_tongquan_en,'cols' => 2,'style' => 'padding-top:0;'),
			);

	//--------------------- Meta Options ---------------------	
	$alias 				= $this->formText ( 'alias', $this->Item['alias'], array ('class' => 'textlong' ) );
	$tags		 		= $this->formTextarea('tags',$this->Item['tags'],array('rows'=>2,'class' => 'txtalong'));
	$meta_title 		= $this->formTextarea('meta_title',$this->Item['meta_title'],array('rows'=>2,'class' => 'txtalong'));
	$meta_description 	= $this->formTextarea('meta_description',$this->Item['meta_description'],array('rows'=>3,'class' => 'txtalong'));
	$meta_keywords 		= $this->formTextarea('meta_keywords',$this->Item['meta_keywords'],array('rows'=>3,'class' => 'txtalong'));
	
	$arrMeta = array(
			array('label' => 'Tổng diện tích','input' => $tongdientich),
			array('label' => 'Mật độ xây dựng','input' => $matdo),
			array('label' => 'Diện tích mặt nước & cây xanh','input' => $dtcayxanh),
			array('label' => 'Diện tích giao thông','input' => $dtgiaothong),
	);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-genex/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php //echo $this->render('admin-genex/sublink/index.php');?>
	<?php echo $errors;?>

<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
		<div class="width-60 fl">
            <script>
				$(document).ready(function() {
					$(".tabs-nav li:first a").addClass('selected');
					$(".tabs:first").css('display','block');
				    $(".tabs-nav li a").click(function() {
				        $(".tabs-nav li a").removeClass('selected');
				        $(this).addClass('selected');
				        $(".tabs").css('display','none');
				        $($(this).attr("rel")).css('display','block');
				        
				    	return false;
				    });
				});
			</script>
            <ul class="tabs-nav clearfix">
				<li><a rel="#tabs-1" href="javascript:void(0)">Vietnamese</a></li>
				<li><a rel="#tabs-2" href="javascript:void(0)">English</a></li>
				
			</ul>
			<fieldset class="adminform tabs" id="tabs-1">
				
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInput);?>
				</table>
			</fieldset>
            <fieldset class="adminform tabs" id="tabs-2">
				
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInputEn);?>
				</table>
			</fieldset>
		</div>
		<div class="width-40 fr">
			<div id="pane-sliders" class="pane-sliders">
				
				<div class="panel">
					<h3 id="metadata-options" class="title pane-toggler-down"><a href="javascript:void(0);"><span>Thông tin diện tích</span></a></h3>
					<div class="panel_content">
						<fieldset class="panelform">
							<table class="panelformlist">
								<?php echo $this->partialLoop('row.php', $arrMeta);?>
							</table>
						</fieldset>
					</div>
				</div>
					
			</div>
		</div>
		<div class="clr"></div>
	</div>
	<!-- END: 	CONTENT -->
</form>