<?php
	//----------------------- INPUT ELEMENTS -------------------//
	$ssFilter 		= $this->arrParam['ssFilter'];
	$selectLanguages = $ssFilter['lang_code'] . $this->formHidden('lang_code',$ssFilter['lang_code']);
	$name 			= $this->formText ( 'name', $this->Item['name'], array ('class' => 'txtlong active', 'onchange'=>"get_alias()") );
    $synopsis			= $this->formTextarea('synopsis', $this->Item['synopsis'],array('rows'=>5,'class' => 'txtalong'));
    $title_slogan 			= $this->formText ( 'title_slogan', $this->Item['title_slogan'], array ('class' => 'txtlong') );
    $synopsis_library_image 			= $this->formTextarea('synopsis_library_image', $this->Item['synopsis_library_image'],array('rows'=>5,'class' => 'txtalong'));
    $gioithieu_vitri			= $this->formTextarea('gioithieu_vitri', $this->Item['gioithieu_vitri'],array('rows'=>5,'class' => 'txtalong'));
    $option 		= array('Không','Có');
	if(isset($this->Item['status'])){
		$trangthai = $this->Item['status'];
	}else{
		$trangthai = 1;
	}
	$status 		= $this->formRadio('status',$trangthai,null,$option, ' ');
    $picture		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture" class="hinh-anh"></div>';
	if(!empty($this->Item['picture'])){
		$picture		= '<div><img src="' . $this->Item['picture'] . '" id="image_picture" class="hinh-anh"></div>';
	}
	$picture 		= $this->cmsUserFiles('picture', $this->Item['picture'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture;
    
    $picture_mobile		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture_mobile" class="hinh-anh"></div>';
	if(!empty($this->Item['picture_mobile'])){
		$picture_mobile		= '<div><img src="' . $this->Item['picture_mobile'] . '" id="image_picture" class="hinh-anh"></div>';
	}
	$picture_mobile 		= $this->cmsUserFiles('picture_mobile', $this->Item['picture_mobile'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture_mobile;
    
    $picture_banner		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture_banner" class="hinh-anh"></div>';
	if(!empty($this->Item['picture_banner'])){
		$picture_banner		= '<div><img src="' . $this->Item['picture_banner'] . '" id="image_picture_banner" class="hinh-anh"></div>';
	}
	$picture_banner 		= $this->cmsUserFiles('picture_banner', $this->Item['picture_banner'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture_banner;
    
    $picture_banner_mobile		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture_banner_mobile" class="hinh-anh"></div>';
	if(!empty($this->Item['picture_banner'])){
		$picture_banner_mobile		= '<div><img src="' . $this->Item['picture_banner_mobile'] . '" id="image_picture_banner_mobile" class="hinh-anh"></div>';
	}
	$picture_banner_mobile 		= $this->cmsUserFiles('picture_banner_mobile', $this->Item['picture_banner_mobile'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture_banner_mobile;
    
    
    $picture_vitri		= '<div><img src="' . $this->imgUrl . '/no-avatar.png" id="image_picture_vitri" class="hinh-anh"></div>';
	if(!empty($this->Item['picture_vitri'])){
		$picture_vitri		= '<div><img src="' . $this->Item['picture'] . '" id="image_picture_vitri" class="hinh-anh"></div>';
	}
	$picture_vitri 		= $this->cmsUserFiles('picture_vitri', $this->Item['picture_vitri'], 'Chọn ảnh', 'images', $options = array('class' => 'txtfile') ) . $picture_vitri;
    
    $template= array('0'=>'--Chọn giao diện--','1'=>'Teamplate1','2'=>'Template2');
    $page	= $this->formSelect('template',$this->Item['template'],array('style'=>'width:250px;'),$template);
   // $slbDiadiemThoigian	= $this->formSelect('time_id',$this->Item['time_id'],array('style'=>'width:250px;'),$this->slbDiadiemThoigian);        
	$order 			= $this->formText ('order', $this->Item['order'], array ('class' => 'txtshort' ) );
   // $color 			= '<div id="colorSelector"><div style="background-color: '.$this->Item['color'].'"></div></div>';
    $color 			= $this->formText ('colorpickerField1', $this->Item['color'], array ('class' => 'txtshort' ) );
	$selectCategory	= $this->cmsSelect('cat_id',$this->Item['cat_id'],$this->slbCategory,array('size'=>0,'style'=>'min-width:200px;'));
	
	
	$arrInput = array(
				array('label' => 'Tên phân khu','input' => $name, 'desc' => '<span class="red">*</span>'),
                array('label' => 'Ảnh đại diện PC','input' => $picture),
                array('label' => 'Ảnh đại diện Mobile','input' => $picture_mobile),
                array('label' => 'Banner PC','input' => $picture_banner),
                array('label' => 'Banner Mobile','input' => $picture_banner_mobile),
                array('label' => 'Giới thiệu tổng quát','input' => $synopsis),
                array('label' => 'Hình ảnh vị trí phân khu','input' => $picture_vitri),
                array('label' => 'Giới thiệu vị trí','input' => $gioithieu_vitri),
                array('label' => 'Sologan phân khu','input' => $title_slogan),
                array('label' => 'Thông tin thư viện ảnh','input' => $synopsis_library_image),
				array('label' => 'Hiển thị','input' => $status),
                array('label' => 'Order','input' => $order),
                
			
			);
	
    //-----------English-----------------------------------------
    $name_en 			= $this->formText ( 'name_en', $this->Item['name_en'], array ('class' => 'txtlong active') );
    $synopsis_en			= $this->formTextarea('synopsis_en', $this->Item['synopsis_en'],array('rows'=>3,'class' => 'txtalong'));
	$gioithieu_vitri_en			= $this->formTextarea('gioithieu_vitri_en', $this->Item['gioithieu_vitri_en'],array('rows'=>5,'class' => 'txtalong'));
    $title_slogan_en 			= $this->formText ( 'title_slogan_en', $this->Item['title_slogan_en'], array ('class' => 'txtlong') );
    $synopsis_library_image_en 			=$this->formTextarea('synopsis_library_image_en', $this->Item['synopsis_library_image_en'],array('rows'=>5,'class' => 'txtalong'));
    
    $arrInput_en = array(
				array('label' => 'Tên phân khu','input' => $name_en, 'desc' => '<span class="red">*</span>'),
                array('label' => 'Giới thiệu tổng quát','input' => $synopsis_en),
                array('label' => 'Giới thiệu vị trí','input' => $gioithieu_vitri_en),
                array('label' => 'Sologan phân khu','input' => $title_slogan_en),
                array('label' => 'Thông tin thư viện ảnh','input' => $synopsis_library_image_en)
			);
	//--------------------- Meta Options ---------------------
	$alias 				= $this->formText ( 'alias', $this->Item['alias'], array ('class' => 'textlong' ) );

	$meta_title 		= $this->formTextarea('meta_title',$this->Item['meta_title'],array('rows'=>2,'class' => 'txtalong'));
	$meta_description 	= $this->formTextarea('meta_description',$this->Item['meta_description'],array('rows'=>3,'class' => 'txtalong'));
	$meta_keywords 		= $this->formTextarea('meta_keywords',$this->Item['meta_keywords'],array('rows'=>3,'class' => 'txtalong'));
	
	$arrMeta = array(
			array('label' => 'Liên kết tĩnh','input' => $alias),
			array('label' => 'Meta Title','input' => $meta_title),
			array('label' => 'Meta Description','input' => $meta_description),
			array('label' => 'Meta Keywords','input' => $meta_keywords),
		);
	
	//-------------------- SESSAGES ERROR ------------------
	if(count($this->messageError)>0){
		$errors = $this->formErrors($this->messageError,array('id'=>'errors'));
	}
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
	<?php echo $this->render('admin-page/toolbar/index.php');?>
 	<div class="clr"></div>
	<?php echo $errors;?>

	<!-- BEGIN: CONTENT -->
	<div class="app_content goc10">
    <script>
		$(document).ready(function() {
			$(".tabs-nav li:first a").addClass('selected');
			$(".tabs:first").css('display','block');
		    $(".tabs-nav li a").click(function() {
		        $(".tabs-nav li a").removeClass('selected');
		        $(this).addClass('selected');
		        $(".tabs").css('display','none');
		        $($(this).attr("rel")).css('display','block');
		        
		    	return false;
		    });
		});
	</script>
		<div class="width-60 fl">           
            <ul class="tabs-nav clearfix">
				<li><a rel="#tabs-1" href="javascript:void(0)">Vietnamese</a></li>
                <li><a rel="#tabs-2" href="javascript:void(0)">English</a></li>
				<li><a rel="#tabs-3" href="javascript:void(0)">Thư viện ảnh</a></li>
				
				<!-- <li><a rel="#tabs-4" href="javascript:void(0)">Video</a></li> -->
			</ul>
            <fieldset class="adminform tabs" id="tabs-1">
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInput);?>
				</table>
			</fieldset>
            <fieldset class="adminform tabs" id="tabs-2">
				<table class="adminformlist">
					<?php echo $this->partialLoop('row.php', $arrInput_en);?>
				</table>
			</fieldset>
            <fieldset class="adminform tabs" id="tabs-3">
				<ul class="adminformlist" id="imagelist">
					<?php
					$numberImage = 0;
					if($this->Item['picture_multi'] != ''){
						$this->Item['picture_multi'] = unserialize($this->Item['picture_multi']);
					}else{
						$this->Item['picture_multi'] = array();
					}
					if(count($this->Item['picture_multi']) > 0){
						$numberImage = count($this->Item['picture_multi']);
						foreach($this->Item['picture_multi'] AS $key => $val){
				?>
					<li id="picture<?php echo $key;?>">
						<script type="text/javascript">
						function openKCFinder<?php echo $key;?>(field) {
							$('#formLoading').removeClass().addClass('loading').fadeIn();
							window.KCFinder = {
								callBack: function(url) {
									field.value = url;
									window.KCFinder = null;
									document.getElementById('image_picture_multi<?php echo $key;?>').src = url;
								}
							};
							window.open('<?php echo SCIPTS_URL . '/media_files/browse.php?type=images&lng=vi';?>', 'kcfinder_textbox','status=0, toolbar=0, location=0, menubar=0, directories=0,resizable=1, scrollbars=0, width=950, height=450' );
							$('#formLoading').removeClass().fadeOut();
						}</script>
						<div>
							<input value="<?php echo $val[0];?>" type="text" name="picture_multi[]" id="picture_multi<?php echo $key;?>" class="txtfile"><a href="javascript:void(0);" onclick="openKCFinder<?php echo $key;?>(appForm.picture_multi<?php echo $key;?>)" class="btnMedia">Chọn ảnh</a><span class="pdl20">Thứ tự <input type="text" name="orderImage[]" style="width: 50px;" value="<?php echo $val[1];?>"></span><span class="pdl20"><a href="javascript:void(0);" onclick="javascript:Delete(<?php echo $key;?>);">[Xóa]</a></span>
						</div>
						<div><img src="<?php echo $val[0];?>" style="width: 60px;" id="image_picture_multi<?php echo $key;?>"></div>
						<div class="clr"></div>
					</li>
					<?php
						}
					} 
					?>
				</ul>
				<div class="fr">
					<a href="javascript:void(0);" onclick="creatImage()" class="btnMedia">Thêm ảnh</a>
				</div>
				<input type="hidden" name="numberImage" id="numberImage" value="<?php echo $numberImage;?>">
				<script type="text/javascript">
					function creatImage(){
						//alert('hic');
						var picture = '<li id="picture{i}">'+
							'<script type="text/javascript">'+
							'function openKCFinder{i}(field) {'+
								'$(\'#formLoading\').removeClass().addClass(\'loading\').fadeIn();'+
								'window.KCFinder = {'+
									'callBack: function(url) {'+
										'field.value = url;'+
										'window.KCFinder = null;'+
										'document.getElementById(\'image_picture_multi{i}\').src = url;'+
									'}'+
								'};'+
								'window.open(\'<?php echo SCIPTS_URL . '/media_files/browse.php?type=images&lng=vi';?>\', \'kcfinder_textbox\',\'status=0, toolbar=0, location=0, menubar=0, directories=0,resizable=1, scrollbars=0, width=950, height=450\');'+
								'$(\'#formLoading\').removeClass().fadeOut();'+
							'}<\/script>'+
							'<div>'+
								'<input value="" type="text" name="picture_multi[]" id="picture_multi{i}" class="txtfile">'+
								'<a href="javascript:void(0);" onclick="openKCFinder{i}(appForm.picture_multi{i})" class="btnMedia">Chọn ảnh</a>'+
								'<span class="pdl20">Thứ tự <input type="text" name="orderImage[]" style="width: 50px;" value="0"></span>'+
								'<span class="pdl20">'+
									'<a href="javascript:void(0);" onclick="javascript:Delete({i});">[Xóa]</a>'+
								'</span>'+
							'</div>'+
							'<div class="clr"></div>'+
							'<div><img src="<?php echo $this->imgUrl . '/no-avatar.png';?>" id="image_picture_multi{i}" class="hinh-anh" style="width: 60px;"></div>'+
						'</li>';
						var i = parseInt($('#numberImage').val());
						var str = picture;
						str = str.replace(/{i}/gi,i);
						str = str.replace(/{i2}/gi,i+1);
						$('#imagelist').append(str);
						$('#numberImage').val(i+1);
					}
					function Delete(i) {
						$('#picture'+i).remove();
					}
				</script>
			</fieldset>
		</div>
		<div class="width-40 fr">
			<div id="pane-sliders" class="pane-sliders">
				
				<div class="panel">
					<h3 id="metadata-options" class="title pane-toggler-down"><a href="javascript:void(0);"><span>Metadata Options</span></a></h3>
					<div class="panel_content">
						<fieldset class="panelform">
							<table class="panelformlist">
								<?php echo $this->partialLoop('row.php', $arrMeta);?>
							</table>
						</fieldset>
					</div>
				</div>
					
			</div>
		</div>
		<div class="clr"></div>
	</div>
	<!-- END: 	CONTENT -->
</form>
